// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseCommand_Type int32

const (
	BaseCommand_CONNECT                       BaseCommand_Type = 2
	BaseCommand_CONNECTED                     BaseCommand_Type = 3
	BaseCommand_PRODUCER                      BaseCommand_Type = 5
	BaseCommand_SEND                          BaseCommand_Type = 6
	BaseCommand_SEND_RECEIPT                  BaseCommand_Type = 7
	BaseCommand_PRODUCER_SUCCESS              BaseCommand_Type = 17
	BaseCommand_PARTITIONED_METADATA          BaseCommand_Type = 21
	BaseCommand_PARTITIONED_METADATA_RESPONSE BaseCommand_Type = 22
	BaseCommand_Lookup                        BaseCommand_Type = 23
	BaseCommand_LookupResponse                BaseCommand_Type = 24
)

var BaseCommand_Type_name = map[int32]string{
	2:  "CONNECT",
	3:  "CONNECTED",
	5:  "PRODUCER",
	6:  "SEND",
	7:  "SEND_RECEIPT",
	17: "PRODUCER_SUCCESS",
	21: "PARTITIONED_METADATA",
	22: "PARTITIONED_METADATA_RESPONSE",
	23: "Lookup",
	24: "LookupResponse",
}

var BaseCommand_Type_value = map[string]int32{
	"CONNECT":                       2,
	"CONNECTED":                     3,
	"PRODUCER":                      5,
	"SEND":                          6,
	"SEND_RECEIPT":                  7,
	"PRODUCER_SUCCESS":              17,
	"PARTITIONED_METADATA":          21,
	"PARTITIONED_METADATA_RESPONSE": 22,
	"Lookup":                        23,
	"LookupResponse":                24,
}

func (x BaseCommand_Type) Enum() *BaseCommand_Type {
	p := new(BaseCommand_Type)
	*p = x
	return p
}

func (x BaseCommand_Type) String() string {
	return proto.EnumName(BaseCommand_Type_name, int32(x))
}

func (x *BaseCommand_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BaseCommand_Type_value, data, "BaseCommand_Type")
	if err != nil {
		return err
	}
	*x = BaseCommand_Type(value)
	return nil
}

func (BaseCommand_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0, 0}
}

type CommandPartitionedTopicMetadataResponse_LookupType int32

const (
	CommandPartitionedTopicMetadataResponse_Success CommandPartitionedTopicMetadataResponse_LookupType = 0
	CommandPartitionedTopicMetadataResponse_Failed  CommandPartitionedTopicMetadataResponse_LookupType = 1
)

var CommandPartitionedTopicMetadataResponse_LookupType_name = map[int32]string{
	0: "Success",
	1: "Failed",
}

var CommandPartitionedTopicMetadataResponse_LookupType_value = map[string]int32{
	"Success": 0,
	"Failed":  1,
}

func (x CommandPartitionedTopicMetadataResponse_LookupType) Enum() *CommandPartitionedTopicMetadataResponse_LookupType {
	p := new(CommandPartitionedTopicMetadataResponse_LookupType)
	*p = x
	return p
}

func (x CommandPartitionedTopicMetadataResponse_LookupType) String() string {
	return proto.EnumName(CommandPartitionedTopicMetadataResponse_LookupType_name, int32(x))
}

func (x *CommandPartitionedTopicMetadataResponse_LookupType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandPartitionedTopicMetadataResponse_LookupType_value, data, "CommandPartitionedTopicMetadataResponse_LookupType")
	if err != nil {
		return err
	}
	*x = CommandPartitionedTopicMetadataResponse_LookupType(value)
	return nil
}

func (CommandPartitionedTopicMetadataResponse_LookupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4, 0}
}

type CommandLookupTopicResponse_LookupType int32

const (
	CommandLookupTopicResponse_Redirect CommandLookupTopicResponse_LookupType = 0
	CommandLookupTopicResponse_Connect  CommandLookupTopicResponse_LookupType = 1
	CommandLookupTopicResponse_Failed   CommandLookupTopicResponse_LookupType = 2
)

var CommandLookupTopicResponse_LookupType_name = map[int32]string{
	0: "Redirect",
	1: "Connect",
	2: "Failed",
}

var CommandLookupTopicResponse_LookupType_value = map[string]int32{
	"Redirect": 0,
	"Connect":  1,
	"Failed":   2,
}

func (x CommandLookupTopicResponse_LookupType) Enum() *CommandLookupTopicResponse_LookupType {
	p := new(CommandLookupTopicResponse_LookupType)
	*p = x
	return p
}

func (x CommandLookupTopicResponse_LookupType) String() string {
	return proto.EnumName(CommandLookupTopicResponse_LookupType_name, int32(x))
}

func (x *CommandLookupTopicResponse_LookupType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandLookupTopicResponse_LookupType_value, data, "CommandLookupTopicResponse_LookupType")
	if err != nil {
		return err
	}
	*x = CommandLookupTopicResponse_LookupType(value)
	return nil
}

func (CommandLookupTopicResponse_LookupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6, 0}
}

//
// package protocol
type BaseCommand struct {
	Type                      *BaseCommand_Type                        `protobuf:"varint,1,req,name=type,enum=BaseCommand_Type" json:"type,omitempty"`
	Connect                   *CommandConnect                          `protobuf:"bytes,2,opt,name=connect" json:"connect,omitempty"`
	Connected                 *CommandConnected                        `protobuf:"bytes,3,opt,name=connected" json:"connected,omitempty"`
	Producer                  *CommandProducer                         `protobuf:"bytes,5,opt,name=producer" json:"producer,omitempty"`
	Send                      *CommandSend                             `protobuf:"bytes,6,opt,name=send" json:"send,omitempty"`
	SendReceipt               *CommandSendReceipt                      `protobuf:"bytes,7,opt,name=send_receipt,json=sendReceipt" json:"send_receipt,omitempty"`
	ProducerSuccess           *CommandProducerSuccess                  `protobuf:"bytes,17,opt,name=producer_success,json=producerSuccess" json:"producer_success,omitempty"`
	PartitionMetadata         *CommandPartitionedTopicMetadata         `protobuf:"bytes,21,opt,name=partitionMetadata" json:"partitionMetadata,omitempty"`
	PartitionMetadataResponse *CommandPartitionedTopicMetadataResponse `protobuf:"bytes,22,opt,name=partitionMetadataResponse" json:"partitionMetadataResponse,omitempty"`
	LookupTopic               *CommandLookupTopic                      `protobuf:"bytes,23,opt,name=lookupTopic" json:"lookupTopic,omitempty"`
	LookupTopicResponse       *CommandLookupTopicResponse              `protobuf:"bytes,24,opt,name=lookupTopicResponse" json:"lookupTopicResponse,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                 `json:"-"`
	XXX_unrecognized          []byte                                   `json:"-"`
	XXX_sizecache             int32                                    `json:"-"`
}

func (m *BaseCommand) Reset()         { *m = BaseCommand{} }
func (m *BaseCommand) String() string { return proto.CompactTextString(m) }
func (*BaseCommand) ProtoMessage()    {}
func (*BaseCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *BaseCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseCommand.Unmarshal(m, b)
}
func (m *BaseCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseCommand.Marshal(b, m, deterministic)
}
func (m *BaseCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseCommand.Merge(m, src)
}
func (m *BaseCommand) XXX_Size() int {
	return xxx_messageInfo_BaseCommand.Size(m)
}
func (m *BaseCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseCommand.DiscardUnknown(m)
}

var xxx_messageInfo_BaseCommand proto.InternalMessageInfo

func (m *BaseCommand) GetType() BaseCommand_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BaseCommand_CONNECT
}

func (m *BaseCommand) GetConnect() *CommandConnect {
	if m != nil {
		return m.Connect
	}
	return nil
}

func (m *BaseCommand) GetConnected() *CommandConnected {
	if m != nil {
		return m.Connected
	}
	return nil
}

func (m *BaseCommand) GetProducer() *CommandProducer {
	if m != nil {
		return m.Producer
	}
	return nil
}

func (m *BaseCommand) GetSend() *CommandSend {
	if m != nil {
		return m.Send
	}
	return nil
}

func (m *BaseCommand) GetSendReceipt() *CommandSendReceipt {
	if m != nil {
		return m.SendReceipt
	}
	return nil
}

func (m *BaseCommand) GetProducerSuccess() *CommandProducerSuccess {
	if m != nil {
		return m.ProducerSuccess
	}
	return nil
}

func (m *BaseCommand) GetPartitionMetadata() *CommandPartitionedTopicMetadata {
	if m != nil {
		return m.PartitionMetadata
	}
	return nil
}

func (m *BaseCommand) GetPartitionMetadataResponse() *CommandPartitionedTopicMetadataResponse {
	if m != nil {
		return m.PartitionMetadataResponse
	}
	return nil
}

func (m *BaseCommand) GetLookupTopic() *CommandLookupTopic {
	if m != nil {
		return m.LookupTopic
	}
	return nil
}

func (m *BaseCommand) GetLookupTopicResponse() *CommandLookupTopicResponse {
	if m != nil {
		return m.LookupTopicResponse
	}
	return nil
}

// handshake logic connection
type CommandConnect struct {
	ClientVersion        *string  `protobuf:"bytes,1,req,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandConnect) Reset()         { *m = CommandConnect{} }
func (m *CommandConnect) String() string { return proto.CompactTextString(m) }
func (*CommandConnect) ProtoMessage()    {}
func (*CommandConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *CommandConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandConnect.Unmarshal(m, b)
}
func (m *CommandConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandConnect.Marshal(b, m, deterministic)
}
func (m *CommandConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandConnect.Merge(m, src)
}
func (m *CommandConnect) XXX_Size() int {
	return xxx_messageInfo_CommandConnect.Size(m)
}
func (m *CommandConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandConnect.DiscardUnknown(m)
}

var xxx_messageInfo_CommandConnect proto.InternalMessageInfo

func (m *CommandConnect) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

type CommandConnected struct {
	ServerVersion        *string  `protobuf:"bytes,1,req,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandConnected) Reset()         { *m = CommandConnected{} }
func (m *CommandConnected) String() string { return proto.CompactTextString(m) }
func (*CommandConnected) ProtoMessage()    {}
func (*CommandConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *CommandConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandConnected.Unmarshal(m, b)
}
func (m *CommandConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandConnected.Marshal(b, m, deterministic)
}
func (m *CommandConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandConnected.Merge(m, src)
}
func (m *CommandConnected) XXX_Size() int {
	return xxx_messageInfo_CommandConnected.Size(m)
}
func (m *CommandConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandConnected.DiscardUnknown(m)
}

var xxx_messageInfo_CommandConnected proto.InternalMessageInfo

func (m *CommandConnected) GetServerVersion() string {
	if m != nil && m.ServerVersion != nil {
		return *m.ServerVersion
	}
	return ""
}

// partitioned topic metadata
type CommandPartitionedTopicMetadata struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	RequestId            *uint64  `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandPartitionedTopicMetadata) Reset()         { *m = CommandPartitionedTopicMetadata{} }
func (m *CommandPartitionedTopicMetadata) String() string { return proto.CompactTextString(m) }
func (*CommandPartitionedTopicMetadata) ProtoMessage()    {}
func (*CommandPartitionedTopicMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *CommandPartitionedTopicMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Unmarshal(m, b)
}
func (m *CommandPartitionedTopicMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Marshal(b, m, deterministic)
}
func (m *CommandPartitionedTopicMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPartitionedTopicMetadata.Merge(m, src)
}
func (m *CommandPartitionedTopicMetadata) XXX_Size() int {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Size(m)
}
func (m *CommandPartitionedTopicMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPartitionedTopicMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPartitionedTopicMetadata proto.InternalMessageInfo

func (m *CommandPartitionedTopicMetadata) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandPartitionedTopicMetadata) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type CommandPartitionedTopicMetadataResponse struct {
	Partitions           *uint32                                             `protobuf:"varint,1,opt,name=partitions" json:"partitions,omitempty"`
	RequestId            *int64                                              `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	Response             *CommandPartitionedTopicMetadataResponse_LookupType `protobuf:"varint,3,opt,name=response,enum=CommandPartitionedTopicMetadataResponse_LookupType" json:"response,omitempty"`
	Message              *string                                             `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *CommandPartitionedTopicMetadataResponse) Reset() {
	*m = CommandPartitionedTopicMetadataResponse{}
}
func (m *CommandPartitionedTopicMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*CommandPartitionedTopicMetadataResponse) ProtoMessage()    {}
func (*CommandPartitionedTopicMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *CommandPartitionedTopicMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Unmarshal(m, b)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Marshal(b, m, deterministic)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Merge(m, src)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Size(m)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPartitionedTopicMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPartitionedTopicMetadataResponse proto.InternalMessageInfo

func (m *CommandPartitionedTopicMetadataResponse) GetPartitions() uint32 {
	if m != nil && m.Partitions != nil {
		return *m.Partitions
	}
	return 0
}

func (m *CommandPartitionedTopicMetadataResponse) GetRequestId() int64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandPartitionedTopicMetadataResponse) GetResponse() CommandPartitionedTopicMetadataResponse_LookupType {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return CommandPartitionedTopicMetadataResponse_Success
}

func (m *CommandPartitionedTopicMetadataResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// lookup topic broker
type CommandLookupTopic struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	RequestId            *uint64  `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandLookupTopic) Reset()         { *m = CommandLookupTopic{} }
func (m *CommandLookupTopic) String() string { return proto.CompactTextString(m) }
func (*CommandLookupTopic) ProtoMessage()    {}
func (*CommandLookupTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}

func (m *CommandLookupTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandLookupTopic.Unmarshal(m, b)
}
func (m *CommandLookupTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandLookupTopic.Marshal(b, m, deterministic)
}
func (m *CommandLookupTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandLookupTopic.Merge(m, src)
}
func (m *CommandLookupTopic) XXX_Size() int {
	return xxx_messageInfo_CommandLookupTopic.Size(m)
}
func (m *CommandLookupTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandLookupTopic.DiscardUnknown(m)
}

var xxx_messageInfo_CommandLookupTopic proto.InternalMessageInfo

func (m *CommandLookupTopic) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandLookupTopic) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type CommandLookupTopicResponse struct {
	BrokerServiceUrl     *string                                `protobuf:"bytes,1,opt,name=brokerServiceUrl" json:"brokerServiceUrl,omitempty"`
	BrokerServiceUrlTls  *string                                `protobuf:"bytes,2,opt,name=brokerServiceUrlTls" json:"brokerServiceUrlTls,omitempty"`
	Response             *CommandLookupTopicResponse_LookupType `protobuf:"varint,3,opt,name=response,enum=CommandLookupTopicResponse_LookupType" json:"response,omitempty"`
	RequestId            *uint64                                `protobuf:"varint,4,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	Message              *string                                `protobuf:"bytes,7,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *CommandLookupTopicResponse) Reset()         { *m = CommandLookupTopicResponse{} }
func (m *CommandLookupTopicResponse) String() string { return proto.CompactTextString(m) }
func (*CommandLookupTopicResponse) ProtoMessage()    {}
func (*CommandLookupTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6}
}

func (m *CommandLookupTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandLookupTopicResponse.Unmarshal(m, b)
}
func (m *CommandLookupTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandLookupTopicResponse.Marshal(b, m, deterministic)
}
func (m *CommandLookupTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandLookupTopicResponse.Merge(m, src)
}
func (m *CommandLookupTopicResponse) XXX_Size() int {
	return xxx_messageInfo_CommandLookupTopicResponse.Size(m)
}
func (m *CommandLookupTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandLookupTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandLookupTopicResponse proto.InternalMessageInfo

func (m *CommandLookupTopicResponse) GetBrokerServiceUrl() string {
	if m != nil && m.BrokerServiceUrl != nil {
		return *m.BrokerServiceUrl
	}
	return ""
}

func (m *CommandLookupTopicResponse) GetBrokerServiceUrlTls() string {
	if m != nil && m.BrokerServiceUrlTls != nil {
		return *m.BrokerServiceUrlTls
	}
	return ""
}

func (m *CommandLookupTopicResponse) GetResponse() CommandLookupTopicResponse_LookupType {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return CommandLookupTopicResponse_Redirect
}

func (m *CommandLookupTopicResponse) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandLookupTopicResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// register producer
type CommandProducer struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	ProducerId           *uint64  `protobuf:"varint,2,req,name=producer_id,json=producerId" json:"producer_id,omitempty"`
	RequestId            *uint64  `protobuf:"varint,3,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ProducerName         *string  `protobuf:"bytes,4,opt,name=producer_name,json=producerName" json:"producer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandProducer) Reset()         { *m = CommandProducer{} }
func (m *CommandProducer) String() string { return proto.CompactTextString(m) }
func (*CommandProducer) ProtoMessage()    {}
func (*CommandProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{7}
}

func (m *CommandProducer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandProducer.Unmarshal(m, b)
}
func (m *CommandProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandProducer.Marshal(b, m, deterministic)
}
func (m *CommandProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandProducer.Merge(m, src)
}
func (m *CommandProducer) XXX_Size() int {
	return xxx_messageInfo_CommandProducer.Size(m)
}
func (m *CommandProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandProducer.DiscardUnknown(m)
}

var xxx_messageInfo_CommandProducer proto.InternalMessageInfo

func (m *CommandProducer) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandProducer) GetProducerId() uint64 {
	if m != nil && m.ProducerId != nil {
		return *m.ProducerId
	}
	return 0
}

func (m *CommandProducer) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandProducer) GetProducerName() string {
	if m != nil && m.ProducerName != nil {
		return *m.ProducerName
	}
	return ""
}

type CommandProducerSuccess struct {
	RequestId            *uint64  `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ProducerName         *string  `protobuf:"bytes,2,req,name=producer_name,json=producerName" json:"producer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandProducerSuccess) Reset()         { *m = CommandProducerSuccess{} }
func (m *CommandProducerSuccess) String() string { return proto.CompactTextString(m) }
func (*CommandProducerSuccess) ProtoMessage()    {}
func (*CommandProducerSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{8}
}

func (m *CommandProducerSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandProducerSuccess.Unmarshal(m, b)
}
func (m *CommandProducerSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandProducerSuccess.Marshal(b, m, deterministic)
}
func (m *CommandProducerSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandProducerSuccess.Merge(m, src)
}
func (m *CommandProducerSuccess) XXX_Size() int {
	return xxx_messageInfo_CommandProducerSuccess.Size(m)
}
func (m *CommandProducerSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandProducerSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_CommandProducerSuccess proto.InternalMessageInfo

func (m *CommandProducerSuccess) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandProducerSuccess) GetProducerName() string {
	if m != nil && m.ProducerName != nil {
		return *m.ProducerName
	}
	return ""
}

// message
type SingleMessageMetadata struct {
	PayloadSize          *int32   `protobuf:"varint,3,req,name=payload_size,json=payloadSize" json:"payload_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleMessageMetadata) Reset()         { *m = SingleMessageMetadata{} }
func (m *SingleMessageMetadata) String() string { return proto.CompactTextString(m) }
func (*SingleMessageMetadata) ProtoMessage()    {}
func (*SingleMessageMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{9}
}

func (m *SingleMessageMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMessageMetadata.Unmarshal(m, b)
}
func (m *SingleMessageMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMessageMetadata.Marshal(b, m, deterministic)
}
func (m *SingleMessageMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMessageMetadata.Merge(m, src)
}
func (m *SingleMessageMetadata) XXX_Size() int {
	return xxx_messageInfo_SingleMessageMetadata.Size(m)
}
func (m *SingleMessageMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMessageMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMessageMetadata proto.InternalMessageInfo

func (m *SingleMessageMetadata) GetPayloadSize() int32 {
	if m != nil && m.PayloadSize != nil {
		return *m.PayloadSize
	}
	return 0
}

type MessageMetadata struct {
	ProducerName         *string  `protobuf:"bytes,1,req,name=producer_name,json=producerName" json:"producer_name,omitempty"`
	SequenceId           *uint64  `protobuf:"varint,2,req,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	PublishTime          *uint64  `protobuf:"varint,3,req,name=publish_time,json=publishTime" json:"publish_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageMetadata) Reset()         { *m = MessageMetadata{} }
func (m *MessageMetadata) String() string { return proto.CompactTextString(m) }
func (*MessageMetadata) ProtoMessage()    {}
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{10}
}

func (m *MessageMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageMetadata.Unmarshal(m, b)
}
func (m *MessageMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageMetadata.Marshal(b, m, deterministic)
}
func (m *MessageMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageMetadata.Merge(m, src)
}
func (m *MessageMetadata) XXX_Size() int {
	return xxx_messageInfo_MessageMetadata.Size(m)
}
func (m *MessageMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_MessageMetadata proto.InternalMessageInfo

func (m *MessageMetadata) GetProducerName() string {
	if m != nil && m.ProducerName != nil {
		return *m.ProducerName
	}
	return ""
}

func (m *MessageMetadata) GetSequenceId() uint64 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

func (m *MessageMetadata) GetPublishTime() uint64 {
	if m != nil && m.PublishTime != nil {
		return *m.PublishTime
	}
	return 0
}

// send
type CommandSend struct {
	ProducerId           *uint64  `protobuf:"varint,1,req,name=producer_id,json=producerId" json:"producer_id,omitempty"`
	SequenceId           *uint64  `protobuf:"varint,2,req,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	NumMessage           *int32   `protobuf:"varint,3,opt,name=num_message,json=numMessage,def=1" json:"num_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandSend) Reset()         { *m = CommandSend{} }
func (m *CommandSend) String() string { return proto.CompactTextString(m) }
func (*CommandSend) ProtoMessage()    {}
func (*CommandSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{11}
}

func (m *CommandSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSend.Unmarshal(m, b)
}
func (m *CommandSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSend.Marshal(b, m, deterministic)
}
func (m *CommandSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSend.Merge(m, src)
}
func (m *CommandSend) XXX_Size() int {
	return xxx_messageInfo_CommandSend.Size(m)
}
func (m *CommandSend) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSend.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSend proto.InternalMessageInfo

const Default_CommandSend_NumMessage int32 = 1

func (m *CommandSend) GetProducerId() uint64 {
	if m != nil && m.ProducerId != nil {
		return *m.ProducerId
	}
	return 0
}

func (m *CommandSend) GetSequenceId() uint64 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

func (m *CommandSend) GetNumMessage() int32 {
	if m != nil && m.NumMessage != nil {
		return *m.NumMessage
	}
	return Default_CommandSend_NumMessage
}

type CommandSendReceipt struct {
	ProducerId           *uint64        `protobuf:"varint,1,req,name=producer_id,json=producerId" json:"producer_id,omitempty"`
	SequenceId           *uint64        `protobuf:"varint,2,req,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	MessageId            *MessageIdData `protobuf:"bytes,3,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommandSendReceipt) Reset()         { *m = CommandSendReceipt{} }
func (m *CommandSendReceipt) String() string { return proto.CompactTextString(m) }
func (*CommandSendReceipt) ProtoMessage()    {}
func (*CommandSendReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{12}
}

func (m *CommandSendReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSendReceipt.Unmarshal(m, b)
}
func (m *CommandSendReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSendReceipt.Marshal(b, m, deterministic)
}
func (m *CommandSendReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSendReceipt.Merge(m, src)
}
func (m *CommandSendReceipt) XXX_Size() int {
	return xxx_messageInfo_CommandSendReceipt.Size(m)
}
func (m *CommandSendReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSendReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSendReceipt proto.InternalMessageInfo

func (m *CommandSendReceipt) GetProducerId() uint64 {
	if m != nil && m.ProducerId != nil {
		return *m.ProducerId
	}
	return 0
}

func (m *CommandSendReceipt) GetSequenceId() uint64 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

func (m *CommandSendReceipt) GetMessageId() *MessageIdData {
	if m != nil {
		return m.MessageId
	}
	return nil
}

type MessageIdData struct {
	LedgerId             *uint64  `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	EntryId              *uint64  `protobuf:"varint,2,req,name=entryId" json:"entryId,omitempty"`
	Partition            *int32   `protobuf:"varint,3,opt,name=partition,def=-1" json:"partition,omitempty"`
	BatchIndex           *int32   `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,def=-1" json:"batch_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageIdData) Reset()         { *m = MessageIdData{} }
func (m *MessageIdData) String() string { return proto.CompactTextString(m) }
func (*MessageIdData) ProtoMessage()    {}
func (*MessageIdData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{13}
}

func (m *MessageIdData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageIdData.Unmarshal(m, b)
}
func (m *MessageIdData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageIdData.Marshal(b, m, deterministic)
}
func (m *MessageIdData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageIdData.Merge(m, src)
}
func (m *MessageIdData) XXX_Size() int {
	return xxx_messageInfo_MessageIdData.Size(m)
}
func (m *MessageIdData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageIdData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageIdData proto.InternalMessageInfo

const Default_MessageIdData_Partition int32 = -1
const Default_MessageIdData_BatchIndex int32 = -1

func (m *MessageIdData) GetLedgerId() uint64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *MessageIdData) GetEntryId() uint64 {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return 0
}

func (m *MessageIdData) GetPartition() int32 {
	if m != nil && m.Partition != nil {
		return *m.Partition
	}
	return Default_MessageIdData_Partition
}

func (m *MessageIdData) GetBatchIndex() int32 {
	if m != nil && m.BatchIndex != nil {
		return *m.BatchIndex
	}
	return Default_MessageIdData_BatchIndex
}

func init() {
	proto.RegisterEnum("BaseCommand_Type", BaseCommand_Type_name, BaseCommand_Type_value)
	proto.RegisterEnum("CommandPartitionedTopicMetadataResponse_LookupType", CommandPartitionedTopicMetadataResponse_LookupType_name, CommandPartitionedTopicMetadataResponse_LookupType_value)
	proto.RegisterEnum("CommandLookupTopicResponse_LookupType", CommandLookupTopicResponse_LookupType_name, CommandLookupTopicResponse_LookupType_value)
	proto.RegisterType((*BaseCommand)(nil), "BaseCommand")
	proto.RegisterType((*CommandConnect)(nil), "CommandConnect")
	proto.RegisterType((*CommandConnected)(nil), "CommandConnected")
	proto.RegisterType((*CommandPartitionedTopicMetadata)(nil), "CommandPartitionedTopicMetadata")
	proto.RegisterType((*CommandPartitionedTopicMetadataResponse)(nil), "CommandPartitionedTopicMetadataResponse")
	proto.RegisterType((*CommandLookupTopic)(nil), "CommandLookupTopic")
	proto.RegisterType((*CommandLookupTopicResponse)(nil), "CommandLookupTopicResponse")
	proto.RegisterType((*CommandProducer)(nil), "CommandProducer")
	proto.RegisterType((*CommandProducerSuccess)(nil), "CommandProducerSuccess")
	proto.RegisterType((*SingleMessageMetadata)(nil), "SingleMessageMetadata")
	proto.RegisterType((*MessageMetadata)(nil), "MessageMetadata")
	proto.RegisterType((*CommandSend)(nil), "CommandSend")
	proto.RegisterType((*CommandSendReceipt)(nil), "CommandSendReceipt")
	proto.RegisterType((*MessageIdData)(nil), "MessageIdData")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 974 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x5e, 0xa7, 0x49, 0x93, 0x1c, 0x27, 0xe9, 0x64, 0xfa, 0x67, 0x16, 0x2d, 0x9b, 0xf5, 0xaa,
	0x10, 0x10, 0x1b, 0xd8, 0xae, 0x00, 0xb1, 0x77, 0x6d, 0x62, 0x24, 0x4b, 0x34, 0x89, 0xc6, 0xee,
	0x5e, 0x21, 0x59, 0xae, 0x7d, 0xe8, 0x5a, 0x1b, 0xff, 0x60, 0x3b, 0x15, 0xed, 0x3d, 0x77, 0x3c,
	0x0a, 0xef, 0xc0, 0x8b, 0xf0, 0x24, 0x5c, 0x21, 0x8f, 0x7f, 0xe2, 0x38, 0x29, 0xad, 0x10, 0x57,
	0xc9, 0x7c, 0xe7, 0x3b, 0x3f, 0x73, 0xe6, 0x3b, 0xc7, 0xd0, 0x0a, 0xae, 0x46, 0x41, 0xe8, 0xc7,
	0xbe, 0xfc, 0xd7, 0x2e, 0x88, 0xe7, 0x66, 0x84, 0x63, 0xdf, 0x75, 0x4d, 0xcf, 0xa6, 0x27, 0x50,
	0x8f, 0x6f, 0x03, 0x94, 0x84, 0x41, 0x6d, 0xd8, 0x3b, 0xed, 0x8f, 0x4a, 0xb6, 0x91, 0x7e, 0x1b,
	0x20, 0xe3, 0x66, 0xfa, 0x39, 0x34, 0x2d, 0xdf, 0xf3, 0xd0, 0x8a, 0xa5, 0xda, 0x40, 0x18, 0x8a,
	0xa7, 0x7b, 0xa3, 0x8c, 0x35, 0x4e, 0x61, 0x96, 0xdb, 0xe9, 0x57, 0xd0, 0xce, 0xfe, 0xa2, 0x2d,
	0xed, 0x70, 0x72, 0xbf, 0x42, 0x46, 0x9b, 0xad, 0x38, 0xf4, 0x4b, 0x68, 0x05, 0xa1, 0x6f, 0x2f,
	0x2d, 0x0c, 0xa5, 0x06, 0xe7, 0x93, 0x9c, 0x3f, 0xcf, 0x70, 0x56, 0x30, 0xe8, 0x00, 0xea, 0x11,
	0x7a, 0xb6, 0xb4, 0xcb, 0x99, 0x9d, 0x9c, 0xa9, 0xa1, 0x67, 0x33, 0x6e, 0xa1, 0xdf, 0x42, 0x27,
	0xf9, 0x35, 0x42, 0xb4, 0xd0, 0x09, 0x62, 0xa9, 0xc9, 0x99, 0xfb, 0x6b, 0xcc, 0xd4, 0xc4, 0xc4,
	0x68, 0x75, 0xa0, 0xe7, 0x40, 0xf2, 0x2c, 0x46, 0xb4, 0xb4, 0x2c, 0x8c, 0x22, 0xa9, 0xcf, 0x7d,
	0x8f, 0xab, 0xf5, 0x68, 0xa9, 0x99, 0xed, 0x05, 0xeb, 0x00, 0x9d, 0x42, 0x3f, 0x30, 0xc3, 0xd8,
	0x89, 0x1d, 0xdf, 0xbb, 0xc0, 0xd8, 0xb4, 0xcd, 0xd8, 0x94, 0x0e, 0x79, 0x90, 0x41, 0x11, 0x24,
	0x27, 0xa0, 0xad, 0xfb, 0x81, 0x63, 0xe5, 0x3c, 0xb6, 0xe9, 0x4a, 0x7f, 0x86, 0x8f, 0x36, 0x40,
	0x86, 0x51, 0xe0, 0x7b, 0x11, 0x4a, 0x47, 0x3c, 0xee, 0xf0, 0xc1, 0xb8, 0x19, 0x9f, 0xdd, 0x1f,
	0x8a, 0x7e, 0x03, 0xe2, 0xc2, 0xf7, 0x3f, 0x2c, 0x03, 0xee, 0x29, 0x1d, 0xaf, 0xb7, 0xec, 0xc7,
	0x95, 0x89, 0x95, 0x79, 0xf4, 0x02, 0xf6, 0x4b, 0xc7, 0xa2, 0x30, 0x89, 0xbb, 0x7f, 0xbc, 0xcd,
	0x3d, 0xaf, 0x65, 0x9b, 0x9f, 0xfc, 0xa7, 0x00, 0xf5, 0x44, 0x74, 0x54, 0x84, 0xe6, 0x78, 0x36,
	0x9d, 0x2a, 0x63, 0x9d, 0xd4, 0x68, 0x17, 0xda, 0xd9, 0x41, 0x99, 0x90, 0x1d, 0xda, 0x81, 0xd6,
	0x9c, 0xcd, 0x26, 0x97, 0x63, 0x85, 0x91, 0x06, 0x6d, 0x41, 0x5d, 0x53, 0xa6, 0x13, 0xb2, 0x4b,
	0x09, 0x74, 0x92, 0x7f, 0x06, 0x53, 0xc6, 0x8a, 0x3a, 0xd7, 0x49, 0x93, 0x1e, 0x00, 0xc9, 0x99,
	0x86, 0x76, 0x39, 0x1e, 0x2b, 0x9a, 0x46, 0xfa, 0x54, 0x82, 0x83, 0xf9, 0x19, 0xd3, 0x55, 0x5d,
	0x9d, 0x4d, 0x95, 0x89, 0x71, 0xa1, 0xe8, 0x67, 0x93, 0x33, 0xfd, 0x8c, 0x1c, 0xd2, 0x17, 0xf0,
	0x6c, 0x9b, 0xc5, 0x60, 0x8a, 0x36, 0x9f, 0x4d, 0x35, 0x85, 0x1c, 0x51, 0x80, 0xdd, 0xf4, 0x36,
	0xe4, 0x98, 0x52, 0xe8, 0xa5, 0xff, 0xf3, 0xfa, 0x89, 0x24, 0x7f, 0x07, 0xbd, 0x75, 0xa9, 0xd3,
	0x13, 0xe8, 0x59, 0x0b, 0x07, 0xbd, 0xd8, 0xb8, 0xc1, 0x30, 0x72, 0x7c, 0x8f, 0x8f, 0x5a, 0x9b,
	0x75, 0x53, 0xf4, 0x5d, 0x0a, 0xca, 0xdf, 0x03, 0xa9, 0xce, 0x48, 0xe2, 0x1a, 0x61, 0x78, 0x83,
	0x61, 0xd5, 0x35, 0x45, 0x73, 0xd7, 0x77, 0xf0, 0xfc, 0x01, 0x05, 0xd0, 0x03, 0x68, 0xc4, 0xfc,
	0x61, 0xd3, 0x00, 0xe9, 0x81, 0x3e, 0x03, 0x08, 0xf1, 0x97, 0x25, 0x46, 0xb1, 0xe1, 0xd8, 0x52,
	0x6d, 0x50, 0x1b, 0xd6, 0x59, 0x3b, 0x43, 0x54, 0x5b, 0xfe, 0x5b, 0x80, 0xcf, 0x1e, 0x29, 0x2d,
	0xfa, 0x09, 0x40, 0x21, 0xae, 0x48, 0x12, 0x06, 0xc2, 0xb0, 0xcb, 0x4a, 0xc8, 0x96, 0x54, 0x3b,
	0xa5, 0x54, 0x74, 0x06, 0xad, 0x30, 0x17, 0x4f, 0xb2, 0x32, 0x7a, 0xa7, 0x6f, 0x1e, 0xab, 0xea,
	0x51, 0xa6, 0xae, 0x64, 0x57, 0x15, 0x41, 0xa8, 0x04, 0x4d, 0x17, 0xa3, 0xc8, 0xbc, 0x46, 0xbe,
	0x52, 0xda, 0x2c, 0x3f, 0xca, 0x27, 0x00, 0x2b, 0x8f, 0x44, 0x68, 0xd9, 0xe8, 0x92, 0x27, 0xc9,
	0xe3, 0xfe, 0x60, 0x3a, 0x0b, 0xb4, 0x89, 0x20, 0xab, 0x40, 0x37, 0xd5, 0xfb, 0xdf, 0xfa, 0xf8,
	0x47, 0x0d, 0x9e, 0xde, 0x3f, 0x09, 0xf4, 0x0b, 0x20, 0x57, 0xa1, 0xff, 0x01, 0x43, 0x0d, 0xc3,
	0x1b, 0xc7, 0xc2, 0xcb, 0x70, 0xc1, 0x1b, 0xd8, 0x66, 0x1b, 0x38, 0xfd, 0x1a, 0xf6, 0xab, 0x98,
	0xbe, 0x88, 0xf8, 0x4a, 0x6e, 0xb3, 0x6d, 0x26, 0x7a, 0xbe, 0xd1, 0xd9, 0x4f, 0xff, 0x65, 0x2c,
	0xb7, 0x37, 0x73, 0xfd, 0x7e, 0xf5, 0xca, 0xfd, 0xca, 0xbd, 0x6e, 0xae, 0xf7, 0xfa, 0xcd, 0x5a,
	0xaf, 0x3b, 0xd0, 0x62, 0x68, 0x3b, 0x21, 0x5a, 0x31, 0x79, 0xc2, 0x47, 0x3c, 0x55, 0x3a, 0x11,
	0x4a, 0x9d, 0xaf, 0xc9, 0xbf, 0x0b, 0xb0, 0x57, 0x59, 0xb7, 0xf7, 0xf4, 0xfd, 0x39, 0x88, 0xc5,
	0xc2, 0x2e, 0x1a, 0x0f, 0x39, 0xa4, 0xda, 0x95, 0xc2, 0x77, 0xaa, 0x85, 0xbf, 0x84, 0x6e, 0xe1,
	0xef, 0x99, 0x2e, 0x4a, 0x75, 0x5e, 0x7e, 0x27, 0x07, 0xa7, 0xa6, 0x8b, 0xf2, 0x4f, 0x70, 0xb4,
	0x7d, 0xf9, 0x57, 0xa2, 0x0b, 0x0f, 0x46, 0xaf, 0xf1, 0xda, 0xd7, 0xa3, 0xbf, 0x85, 0x43, 0xcd,
	0xf1, 0xae, 0x17, 0x78, 0x91, 0xb6, 0xac, 0x98, 0xd8, 0x17, 0xd0, 0x09, 0xcc, 0xdb, 0x85, 0x6f,
	0xda, 0x46, 0xe4, 0xdc, 0x21, 0x2f, 0xbe, 0xc1, 0xc4, 0x0c, 0xd3, 0x9c, 0x3b, 0x94, 0xef, 0x60,
	0xaf, 0xea, 0xb5, 0x91, 0x53, 0xd8, 0xcc, 0x99, 0xb4, 0x2d, 0x4a, 0xaa, 0xf4, 0x2c, 0x2c, 0xb5,
	0x2d, 0x87, 0x54, 0x9b, 0xe7, 0x5e, 0x5e, 0x2d, 0x9c, 0xe8, 0xbd, 0x11, 0x3b, 0x2e, 0x66, 0x8d,
	0x13, 0x33, 0x4c, 0x77, 0x5c, 0x94, 0x23, 0x10, 0x4b, 0x9f, 0xd3, 0xea, 0x4b, 0x08, 0x1b, 0x2f,
	0xf1, 0x60, 0x4e, 0x19, 0x44, 0x6f, 0xe9, 0x1a, 0xb9, 0x90, 0x12, 0xa9, 0x36, 0xde, 0x0a, 0xaf,
	0x19, 0x78, 0x4b, 0x37, 0xbb, 0xa5, 0xfc, 0x9b, 0x50, 0x0c, 0x65, 0xe9, 0x23, 0xfe, 0x3f, 0x24,
	0x7f, 0x05, 0x90, 0x25, 0x4e, 0x75, 0x92, 0x7c, 0xbd, 0x7a, 0xa3, 0x2c, 0xad, 0x6a, 0x4f, 0x92,
	0x75, 0xd3, 0x76, 0xf3, 0x63, 0xa2, 0xd0, 0xee, 0x9a, 0x91, 0x3e, 0x85, 0xd6, 0x02, 0xed, 0xeb,
	0x24, 0x5b, 0x96, 0xbf, 0x38, 0x27, 0xe3, 0x81, 0x5e, 0x1c, 0xde, 0xaa, 0x79, 0xe6, 0xfc, 0x48,
	0x07, 0xd0, 0x2e, 0x56, 0x64, 0x76, 0xe3, 0xda, 0xab, 0xd7, 0x6c, 0x05, 0xd2, 0x97, 0x20, 0x5e,
	0x99, 0xb1, 0xf5, 0xde, 0x70, 0x3c, 0x1b, 0x7f, 0xe5, 0xfa, 0x4c, 0x39, 0xc0, 0x61, 0x35, 0x41,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x39, 0xe5, 0x12, 0xdd, 0x09, 0x00, 0x00,
}
