// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// others
//
type ServerError int32

const (
	ServerError_UnknownError                          ServerError = 0
	ServerError_MetadataError                         ServerError = 1
	ServerError_PersistenceError                      ServerError = 2
	ServerError_AuthenticationError                   ServerError = 3
	ServerError_AuthorizationError                    ServerError = 4
	ServerError_ConsumerBusy                          ServerError = 5
	ServerError_ServiceNotReady                       ServerError = 6
	ServerError_ProducerBlockedQuotaExceededError     ServerError = 7
	ServerError_ProducerBlockedQuotaExceededException ServerError = 8
	ServerError_ChecksumError                         ServerError = 9
	ServerError_UnsupportedVersionError               ServerError = 10
	ServerError_TopicNotFound                         ServerError = 11
	ServerError_SubscriptionNotFound                  ServerError = 12
	ServerError_ConsumerNotFound                      ServerError = 13
	ServerError_TooManyRequests                       ServerError = 14
	ServerError_TopicTerminatedError                  ServerError = 15
	ServerError_ProducerBusy                          ServerError = 16
	ServerError_InvalidTopicName                      ServerError = 17
	ServerError_IncompatibleSchema                    ServerError = 18
	ServerError_ConsumerAssignError                   ServerError = 19
	ServerError_TransactionCoordinatorNotFound        ServerError = 20
	ServerError_InvalidTxnStatus                      ServerError = 21
)

var ServerError_name = map[int32]string{
	0:  "UnknownError",
	1:  "MetadataError",
	2:  "PersistenceError",
	3:  "AuthenticationError",
	4:  "AuthorizationError",
	5:  "ConsumerBusy",
	6:  "ServiceNotReady",
	7:  "ProducerBlockedQuotaExceededError",
	8:  "ProducerBlockedQuotaExceededException",
	9:  "ChecksumError",
	10: "UnsupportedVersionError",
	11: "TopicNotFound",
	12: "SubscriptionNotFound",
	13: "ConsumerNotFound",
	14: "TooManyRequests",
	15: "TopicTerminatedError",
	16: "ProducerBusy",
	17: "InvalidTopicName",
	18: "IncompatibleSchema",
	19: "ConsumerAssignError",
	20: "TransactionCoordinatorNotFound",
	21: "InvalidTxnStatus",
}

var ServerError_value = map[string]int32{
	"UnknownError":                          0,
	"MetadataError":                         1,
	"PersistenceError":                      2,
	"AuthenticationError":                   3,
	"AuthorizationError":                    4,
	"ConsumerBusy":                          5,
	"ServiceNotReady":                       6,
	"ProducerBlockedQuotaExceededError":     7,
	"ProducerBlockedQuotaExceededException": 8,
	"ChecksumError":                         9,
	"UnsupportedVersionError":               10,
	"TopicNotFound":                         11,
	"SubscriptionNotFound":                  12,
	"ConsumerNotFound":                      13,
	"TooManyRequests":                       14,
	"TopicTerminatedError":                  15,
	"ProducerBusy":                          16,
	"InvalidTopicName":                      17,
	"IncompatibleSchema":                    18,
	"ConsumerAssignError":                   19,
	"TransactionCoordinatorNotFound":        20,
	"InvalidTxnStatus":                      21,
}

func (x ServerError) Enum() *ServerError {
	p := new(ServerError)
	*p = x
	return p
}

func (x ServerError) String() string {
	return proto.EnumName(ServerError_name, int32(x))
}

func (x *ServerError) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerError_value, data, "ServerError")
	if err != nil {
		return err
	}
	*x = ServerError(value)
	return nil
}

func (ServerError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

type BaseCommand_Type int32

const (
	BaseCommand_CONNECT                       BaseCommand_Type = 2
	BaseCommand_CONNECTED                     BaseCommand_Type = 3
	BaseCommand_SUBSCRIBE                     BaseCommand_Type = 4
	BaseCommand_PRODUCER                      BaseCommand_Type = 5
	BaseCommand_SEND                          BaseCommand_Type = 6
	BaseCommand_SEND_RECEIPT                  BaseCommand_Type = 7
	BaseCommand_MESSAGE                       BaseCommand_Type = 9
	BaseCommand_FLOW                          BaseCommand_Type = 11
	BaseCommand_SUCCESS                       BaseCommand_Type = 13
	BaseCommand_ERROR                         BaseCommand_Type = 14
	BaseCommand_CLOSE_PRODUCER                BaseCommand_Type = 15
	BaseCommand_PRODUCER_SUCCESS              BaseCommand_Type = 17
	BaseCommand_PARTITIONED_METADATA          BaseCommand_Type = 21
	BaseCommand_PARTITIONED_METADATA_RESPONSE BaseCommand_Type = 22
	BaseCommand_Lookup                        BaseCommand_Type = 23
	BaseCommand_LookupResponse                BaseCommand_Type = 24
	BaseCommand_CONSUMER_STATS_RESPONSE       BaseCommand_Type = 26
)

var BaseCommand_Type_name = map[int32]string{
	2:  "CONNECT",
	3:  "CONNECTED",
	4:  "SUBSCRIBE",
	5:  "PRODUCER",
	6:  "SEND",
	7:  "SEND_RECEIPT",
	9:  "MESSAGE",
	11: "FLOW",
	13: "SUCCESS",
	14: "ERROR",
	15: "CLOSE_PRODUCER",
	17: "PRODUCER_SUCCESS",
	21: "PARTITIONED_METADATA",
	22: "PARTITIONED_METADATA_RESPONSE",
	23: "Lookup",
	24: "LookupResponse",
	26: "CONSUMER_STATS_RESPONSE",
}

var BaseCommand_Type_value = map[string]int32{
	"CONNECT":                       2,
	"CONNECTED":                     3,
	"SUBSCRIBE":                     4,
	"PRODUCER":                      5,
	"SEND":                          6,
	"SEND_RECEIPT":                  7,
	"MESSAGE":                       9,
	"FLOW":                          11,
	"SUCCESS":                       13,
	"ERROR":                         14,
	"CLOSE_PRODUCER":                15,
	"PRODUCER_SUCCESS":              17,
	"PARTITIONED_METADATA":          21,
	"PARTITIONED_METADATA_RESPONSE": 22,
	"Lookup":                        23,
	"LookupResponse":                24,
	"CONSUMER_STATS_RESPONSE":       26,
}

func (x BaseCommand_Type) Enum() *BaseCommand_Type {
	p := new(BaseCommand_Type)
	*p = x
	return p
}

func (x BaseCommand_Type) String() string {
	return proto.EnumName(BaseCommand_Type_name, int32(x))
}

func (x *BaseCommand_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BaseCommand_Type_value, data, "BaseCommand_Type")
	if err != nil {
		return err
	}
	*x = BaseCommand_Type(value)
	return nil
}

func (BaseCommand_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0, 0}
}

type CommandPartitionedTopicMetadataResponse_LookupType int32

const (
	CommandPartitionedTopicMetadataResponse_Success CommandPartitionedTopicMetadataResponse_LookupType = 0
	CommandPartitionedTopicMetadataResponse_Failed  CommandPartitionedTopicMetadataResponse_LookupType = 1
)

var CommandPartitionedTopicMetadataResponse_LookupType_name = map[int32]string{
	0: "Success",
	1: "Failed",
}

var CommandPartitionedTopicMetadataResponse_LookupType_value = map[string]int32{
	"Success": 0,
	"Failed":  1,
}

func (x CommandPartitionedTopicMetadataResponse_LookupType) Enum() *CommandPartitionedTopicMetadataResponse_LookupType {
	p := new(CommandPartitionedTopicMetadataResponse_LookupType)
	*p = x
	return p
}

func (x CommandPartitionedTopicMetadataResponse_LookupType) String() string {
	return proto.EnumName(CommandPartitionedTopicMetadataResponse_LookupType_name, int32(x))
}

func (x *CommandPartitionedTopicMetadataResponse_LookupType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandPartitionedTopicMetadataResponse_LookupType_value, data, "CommandPartitionedTopicMetadataResponse_LookupType")
	if err != nil {
		return err
	}
	*x = CommandPartitionedTopicMetadataResponse_LookupType(value)
	return nil
}

func (CommandPartitionedTopicMetadataResponse_LookupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6, 0}
}

type CommandLookupTopicResponse_LookupType int32

const (
	CommandLookupTopicResponse_Redirect CommandLookupTopicResponse_LookupType = 0
	CommandLookupTopicResponse_Connect  CommandLookupTopicResponse_LookupType = 1
	CommandLookupTopicResponse_Failed   CommandLookupTopicResponse_LookupType = 2
)

var CommandLookupTopicResponse_LookupType_name = map[int32]string{
	0: "Redirect",
	1: "Connect",
	2: "Failed",
}

var CommandLookupTopicResponse_LookupType_value = map[string]int32{
	"Redirect": 0,
	"Connect":  1,
	"Failed":   2,
}

func (x CommandLookupTopicResponse_LookupType) Enum() *CommandLookupTopicResponse_LookupType {
	p := new(CommandLookupTopicResponse_LookupType)
	*p = x
	return p
}

func (x CommandLookupTopicResponse_LookupType) String() string {
	return proto.EnumName(CommandLookupTopicResponse_LookupType_name, int32(x))
}

func (x *CommandLookupTopicResponse_LookupType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandLookupTopicResponse_LookupType_value, data, "CommandLookupTopicResponse_LookupType")
	if err != nil {
		return err
	}
	*x = CommandLookupTopicResponse_LookupType(value)
	return nil
}

func (CommandLookupTopicResponse_LookupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{8, 0}
}

type CommandSubscribe_SubType int32

const (
	CommandSubscribe_Exclusive CommandSubscribe_SubType = 0
)

var CommandSubscribe_SubType_name = map[int32]string{
	0: "Exclusive",
}

var CommandSubscribe_SubType_value = map[string]int32{
	"Exclusive": 0,
}

func (x CommandSubscribe_SubType) Enum() *CommandSubscribe_SubType {
	p := new(CommandSubscribe_SubType)
	*p = x
	return p
}

func (x CommandSubscribe_SubType) String() string {
	return proto.EnumName(CommandSubscribe_SubType_name, int32(x))
}

func (x *CommandSubscribe_SubType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandSubscribe_SubType_value, data, "CommandSubscribe_SubType")
	if err != nil {
		return err
	}
	*x = CommandSubscribe_SubType(value)
	return nil
}

func (CommandSubscribe_SubType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{18, 0}
}

type CommandSubscribe_InitialPosition int32

const (
	CommandSubscribe_Latest   CommandSubscribe_InitialPosition = 0
	CommandSubscribe_Earliest CommandSubscribe_InitialPosition = 1
)

var CommandSubscribe_InitialPosition_name = map[int32]string{
	0: "Latest",
	1: "Earliest",
}

var CommandSubscribe_InitialPosition_value = map[string]int32{
	"Latest":   0,
	"Earliest": 1,
}

func (x CommandSubscribe_InitialPosition) Enum() *CommandSubscribe_InitialPosition {
	p := new(CommandSubscribe_InitialPosition)
	*p = x
	return p
}

func (x CommandSubscribe_InitialPosition) String() string {
	return proto.EnumName(CommandSubscribe_InitialPosition_name, int32(x))
}

func (x *CommandSubscribe_InitialPosition) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandSubscribe_InitialPosition_value, data, "CommandSubscribe_InitialPosition")
	if err != nil {
		return err
	}
	*x = CommandSubscribe_InitialPosition(value)
	return nil
}

func (CommandSubscribe_InitialPosition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{18, 1}
}

//
// package protocol
type BaseCommand struct {
	Type                      *BaseCommand_Type                        `protobuf:"varint,1,req,name=type,enum=BaseCommand_Type" json:"type,omitempty"`
	Connect                   *CommandConnect                          `protobuf:"bytes,2,opt,name=connect" json:"connect,omitempty"`
	Connected                 *CommandConnected                        `protobuf:"bytes,3,opt,name=connected" json:"connected,omitempty"`
	Subscribe                 *CommandSubscribe                        `protobuf:"bytes,4,opt,name=subscribe" json:"subscribe,omitempty"`
	Producer                  *CommandProducer                         `protobuf:"bytes,5,opt,name=producer" json:"producer,omitempty"`
	Send                      *CommandSend                             `protobuf:"bytes,6,opt,name=send" json:"send,omitempty"`
	SendReceipt               *CommandSendReceipt                      `protobuf:"bytes,7,opt,name=send_receipt,json=sendReceipt" json:"send_receipt,omitempty"`
	Message                   *CommandMessage                          `protobuf:"bytes,9,opt,name=message" json:"message,omitempty"`
	Flow                      *CommandFlow                             `protobuf:"bytes,11,opt,name=flow" json:"flow,omitempty"`
	Success                   *CommandSuccess                          `protobuf:"bytes,13,opt,name=success" json:"success,omitempty"`
	Error                     *CommandError                            `protobuf:"bytes,14,opt,name=error" json:"error,omitempty"`
	CloseProducer             *CommandCloseProducer                    `protobuf:"bytes,15,opt,name=close_producer,json=closeProducer" json:"close_producer,omitempty"`
	ProducerSuccess           *CommandProducerSuccess                  `protobuf:"bytes,17,opt,name=producer_success,json=producerSuccess" json:"producer_success,omitempty"`
	PartitionMetadata         *CommandPartitionedTopicMetadata         `protobuf:"bytes,21,opt,name=partitionMetadata" json:"partitionMetadata,omitempty"`
	PartitionMetadataResponse *CommandPartitionedTopicMetadataResponse `protobuf:"bytes,22,opt,name=partitionMetadataResponse" json:"partitionMetadataResponse,omitempty"`
	LookupTopic               *CommandLookupTopic                      `protobuf:"bytes,23,opt,name=lookupTopic" json:"lookupTopic,omitempty"`
	LookupTopicResponse       *CommandLookupTopicResponse              `protobuf:"bytes,24,opt,name=lookupTopicResponse" json:"lookupTopicResponse,omitempty"`
	ConsumerStatsResponse     *CommandConsumerStatsResponse            `protobuf:"bytes,26,opt,name=consumerStatsResponse" json:"consumerStatsResponse,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                 `json:"-"`
	XXX_unrecognized          []byte                                   `json:"-"`
	XXX_sizecache             int32                                    `json:"-"`
}

func (m *BaseCommand) Reset()         { *m = BaseCommand{} }
func (m *BaseCommand) String() string { return proto.CompactTextString(m) }
func (*BaseCommand) ProtoMessage()    {}
func (*BaseCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *BaseCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseCommand.Unmarshal(m, b)
}
func (m *BaseCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseCommand.Marshal(b, m, deterministic)
}
func (m *BaseCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseCommand.Merge(m, src)
}
func (m *BaseCommand) XXX_Size() int {
	return xxx_messageInfo_BaseCommand.Size(m)
}
func (m *BaseCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseCommand.DiscardUnknown(m)
}

var xxx_messageInfo_BaseCommand proto.InternalMessageInfo

func (m *BaseCommand) GetType() BaseCommand_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BaseCommand_CONNECT
}

func (m *BaseCommand) GetConnect() *CommandConnect {
	if m != nil {
		return m.Connect
	}
	return nil
}

func (m *BaseCommand) GetConnected() *CommandConnected {
	if m != nil {
		return m.Connected
	}
	return nil
}

func (m *BaseCommand) GetSubscribe() *CommandSubscribe {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

func (m *BaseCommand) GetProducer() *CommandProducer {
	if m != nil {
		return m.Producer
	}
	return nil
}

func (m *BaseCommand) GetSend() *CommandSend {
	if m != nil {
		return m.Send
	}
	return nil
}

func (m *BaseCommand) GetSendReceipt() *CommandSendReceipt {
	if m != nil {
		return m.SendReceipt
	}
	return nil
}

func (m *BaseCommand) GetMessage() *CommandMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *BaseCommand) GetFlow() *CommandFlow {
	if m != nil {
		return m.Flow
	}
	return nil
}

func (m *BaseCommand) GetSuccess() *CommandSuccess {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *BaseCommand) GetError() *CommandError {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BaseCommand) GetCloseProducer() *CommandCloseProducer {
	if m != nil {
		return m.CloseProducer
	}
	return nil
}

func (m *BaseCommand) GetProducerSuccess() *CommandProducerSuccess {
	if m != nil {
		return m.ProducerSuccess
	}
	return nil
}

func (m *BaseCommand) GetPartitionMetadata() *CommandPartitionedTopicMetadata {
	if m != nil {
		return m.PartitionMetadata
	}
	return nil
}

func (m *BaseCommand) GetPartitionMetadataResponse() *CommandPartitionedTopicMetadataResponse {
	if m != nil {
		return m.PartitionMetadataResponse
	}
	return nil
}

func (m *BaseCommand) GetLookupTopic() *CommandLookupTopic {
	if m != nil {
		return m.LookupTopic
	}
	return nil
}

func (m *BaseCommand) GetLookupTopicResponse() *CommandLookupTopicResponse {
	if m != nil {
		return m.LookupTopicResponse
	}
	return nil
}

func (m *BaseCommand) GetConsumerStatsResponse() *CommandConsumerStatsResponse {
	if m != nil {
		return m.ConsumerStatsResponse
	}
	return nil
}

//
// general
//
type CommandSuccess struct {
	RequestId            *uint64  `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandSuccess) Reset()         { *m = CommandSuccess{} }
func (m *CommandSuccess) String() string { return proto.CompactTextString(m) }
func (*CommandSuccess) ProtoMessage()    {}
func (*CommandSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *CommandSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSuccess.Unmarshal(m, b)
}
func (m *CommandSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSuccess.Marshal(b, m, deterministic)
}
func (m *CommandSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSuccess.Merge(m, src)
}
func (m *CommandSuccess) XXX_Size() int {
	return xxx_messageInfo_CommandSuccess.Size(m)
}
func (m *CommandSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSuccess proto.InternalMessageInfo

func (m *CommandSuccess) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type CommandError struct {
	RequestId            *uint64      `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	Error                *ServerError `protobuf:"varint,2,req,name=error,enum=ServerError" json:"error,omitempty"`
	Message              *string      `protobuf:"bytes,3,req,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CommandError) Reset()         { *m = CommandError{} }
func (m *CommandError) String() string { return proto.CompactTextString(m) }
func (*CommandError) ProtoMessage()    {}
func (*CommandError) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *CommandError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandError.Unmarshal(m, b)
}
func (m *CommandError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandError.Marshal(b, m, deterministic)
}
func (m *CommandError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandError.Merge(m, src)
}
func (m *CommandError) XXX_Size() int {
	return xxx_messageInfo_CommandError.Size(m)
}
func (m *CommandError) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandError.DiscardUnknown(m)
}

var xxx_messageInfo_CommandError proto.InternalMessageInfo

func (m *CommandError) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandError) GetError() ServerError {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ServerError_UnknownError
}

func (m *CommandError) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

//
// connection
//
// handshake logic connection
type CommandConnect struct {
	ClientVersion        *string  `protobuf:"bytes,1,req,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandConnect) Reset()         { *m = CommandConnect{} }
func (m *CommandConnect) String() string { return proto.CompactTextString(m) }
func (*CommandConnect) ProtoMessage()    {}
func (*CommandConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *CommandConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandConnect.Unmarshal(m, b)
}
func (m *CommandConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandConnect.Marshal(b, m, deterministic)
}
func (m *CommandConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandConnect.Merge(m, src)
}
func (m *CommandConnect) XXX_Size() int {
	return xxx_messageInfo_CommandConnect.Size(m)
}
func (m *CommandConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandConnect.DiscardUnknown(m)
}

var xxx_messageInfo_CommandConnect proto.InternalMessageInfo

func (m *CommandConnect) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

type CommandConnected struct {
	ServerVersion        *string  `protobuf:"bytes,1,req,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandConnected) Reset()         { *m = CommandConnected{} }
func (m *CommandConnected) String() string { return proto.CompactTextString(m) }
func (*CommandConnected) ProtoMessage()    {}
func (*CommandConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *CommandConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandConnected.Unmarshal(m, b)
}
func (m *CommandConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandConnected.Marshal(b, m, deterministic)
}
func (m *CommandConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandConnected.Merge(m, src)
}
func (m *CommandConnected) XXX_Size() int {
	return xxx_messageInfo_CommandConnected.Size(m)
}
func (m *CommandConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandConnected.DiscardUnknown(m)
}

var xxx_messageInfo_CommandConnected proto.InternalMessageInfo

func (m *CommandConnected) GetServerVersion() string {
	if m != nil && m.ServerVersion != nil {
		return *m.ServerVersion
	}
	return ""
}

//
// lookup
//
// partitioned topic metadata
type CommandPartitionedTopicMetadata struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	RequestId            *uint64  `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandPartitionedTopicMetadata) Reset()         { *m = CommandPartitionedTopicMetadata{} }
func (m *CommandPartitionedTopicMetadata) String() string { return proto.CompactTextString(m) }
func (*CommandPartitionedTopicMetadata) ProtoMessage()    {}
func (*CommandPartitionedTopicMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}

func (m *CommandPartitionedTopicMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Unmarshal(m, b)
}
func (m *CommandPartitionedTopicMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Marshal(b, m, deterministic)
}
func (m *CommandPartitionedTopicMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPartitionedTopicMetadata.Merge(m, src)
}
func (m *CommandPartitionedTopicMetadata) XXX_Size() int {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Size(m)
}
func (m *CommandPartitionedTopicMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPartitionedTopicMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPartitionedTopicMetadata proto.InternalMessageInfo

func (m *CommandPartitionedTopicMetadata) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandPartitionedTopicMetadata) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type CommandPartitionedTopicMetadataResponse struct {
	Partitions           *uint32                                             `protobuf:"varint,1,opt,name=partitions" json:"partitions,omitempty"`
	RequestId            *int64                                              `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	Response             *CommandPartitionedTopicMetadataResponse_LookupType `protobuf:"varint,3,opt,name=response,enum=CommandPartitionedTopicMetadataResponse_LookupType" json:"response,omitempty"`
	Message              *string                                             `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *CommandPartitionedTopicMetadataResponse) Reset() {
	*m = CommandPartitionedTopicMetadataResponse{}
}
func (m *CommandPartitionedTopicMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*CommandPartitionedTopicMetadataResponse) ProtoMessage()    {}
func (*CommandPartitionedTopicMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6}
}

func (m *CommandPartitionedTopicMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Unmarshal(m, b)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Marshal(b, m, deterministic)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Merge(m, src)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Size(m)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPartitionedTopicMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPartitionedTopicMetadataResponse proto.InternalMessageInfo

func (m *CommandPartitionedTopicMetadataResponse) GetPartitions() uint32 {
	if m != nil && m.Partitions != nil {
		return *m.Partitions
	}
	return 0
}

func (m *CommandPartitionedTopicMetadataResponse) GetRequestId() int64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandPartitionedTopicMetadataResponse) GetResponse() CommandPartitionedTopicMetadataResponse_LookupType {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return CommandPartitionedTopicMetadataResponse_Success
}

func (m *CommandPartitionedTopicMetadataResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// lookup topic broker
type CommandLookupTopic struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	RequestId            *uint64  `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandLookupTopic) Reset()         { *m = CommandLookupTopic{} }
func (m *CommandLookupTopic) String() string { return proto.CompactTextString(m) }
func (*CommandLookupTopic) ProtoMessage()    {}
func (*CommandLookupTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{7}
}

func (m *CommandLookupTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandLookupTopic.Unmarshal(m, b)
}
func (m *CommandLookupTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandLookupTopic.Marshal(b, m, deterministic)
}
func (m *CommandLookupTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandLookupTopic.Merge(m, src)
}
func (m *CommandLookupTopic) XXX_Size() int {
	return xxx_messageInfo_CommandLookupTopic.Size(m)
}
func (m *CommandLookupTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandLookupTopic.DiscardUnknown(m)
}

var xxx_messageInfo_CommandLookupTopic proto.InternalMessageInfo

func (m *CommandLookupTopic) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandLookupTopic) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type CommandLookupTopicResponse struct {
	BrokerServiceUrl     *string                                `protobuf:"bytes,1,opt,name=brokerServiceUrl" json:"brokerServiceUrl,omitempty"`
	BrokerServiceUrlTls  *string                                `protobuf:"bytes,2,opt,name=brokerServiceUrlTls" json:"brokerServiceUrlTls,omitempty"`
	Response             *CommandLookupTopicResponse_LookupType `protobuf:"varint,3,opt,name=response,enum=CommandLookupTopicResponse_LookupType" json:"response,omitempty"`
	RequestId            *uint64                                `protobuf:"varint,4,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	Message              *string                                `protobuf:"bytes,7,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *CommandLookupTopicResponse) Reset()         { *m = CommandLookupTopicResponse{} }
func (m *CommandLookupTopicResponse) String() string { return proto.CompactTextString(m) }
func (*CommandLookupTopicResponse) ProtoMessage()    {}
func (*CommandLookupTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{8}
}

func (m *CommandLookupTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandLookupTopicResponse.Unmarshal(m, b)
}
func (m *CommandLookupTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandLookupTopicResponse.Marshal(b, m, deterministic)
}
func (m *CommandLookupTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandLookupTopicResponse.Merge(m, src)
}
func (m *CommandLookupTopicResponse) XXX_Size() int {
	return xxx_messageInfo_CommandLookupTopicResponse.Size(m)
}
func (m *CommandLookupTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandLookupTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandLookupTopicResponse proto.InternalMessageInfo

func (m *CommandLookupTopicResponse) GetBrokerServiceUrl() string {
	if m != nil && m.BrokerServiceUrl != nil {
		return *m.BrokerServiceUrl
	}
	return ""
}

func (m *CommandLookupTopicResponse) GetBrokerServiceUrlTls() string {
	if m != nil && m.BrokerServiceUrlTls != nil {
		return *m.BrokerServiceUrlTls
	}
	return ""
}

func (m *CommandLookupTopicResponse) GetResponse() CommandLookupTopicResponse_LookupType {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return CommandLookupTopicResponse_Redirect
}

func (m *CommandLookupTopicResponse) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandLookupTopicResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

//
// produce
//
// register producer
type CommandProducer struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	ProducerId           *uint64  `protobuf:"varint,2,req,name=producer_id,json=producerId" json:"producer_id,omitempty"`
	RequestId            *uint64  `protobuf:"varint,3,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ProducerName         *string  `protobuf:"bytes,4,opt,name=producer_name,json=producerName" json:"producer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandProducer) Reset()         { *m = CommandProducer{} }
func (m *CommandProducer) String() string { return proto.CompactTextString(m) }
func (*CommandProducer) ProtoMessage()    {}
func (*CommandProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{9}
}

func (m *CommandProducer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandProducer.Unmarshal(m, b)
}
func (m *CommandProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandProducer.Marshal(b, m, deterministic)
}
func (m *CommandProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandProducer.Merge(m, src)
}
func (m *CommandProducer) XXX_Size() int {
	return xxx_messageInfo_CommandProducer.Size(m)
}
func (m *CommandProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandProducer.DiscardUnknown(m)
}

var xxx_messageInfo_CommandProducer proto.InternalMessageInfo

func (m *CommandProducer) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandProducer) GetProducerId() uint64 {
	if m != nil && m.ProducerId != nil {
		return *m.ProducerId
	}
	return 0
}

func (m *CommandProducer) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandProducer) GetProducerName() string {
	if m != nil && m.ProducerName != nil {
		return *m.ProducerName
	}
	return ""
}

type CommandProducerSuccess struct {
	RequestId            *uint64  `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ProducerName         *string  `protobuf:"bytes,2,req,name=producer_name,json=producerName" json:"producer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandProducerSuccess) Reset()         { *m = CommandProducerSuccess{} }
func (m *CommandProducerSuccess) String() string { return proto.CompactTextString(m) }
func (*CommandProducerSuccess) ProtoMessage()    {}
func (*CommandProducerSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{10}
}

func (m *CommandProducerSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandProducerSuccess.Unmarshal(m, b)
}
func (m *CommandProducerSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandProducerSuccess.Marshal(b, m, deterministic)
}
func (m *CommandProducerSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandProducerSuccess.Merge(m, src)
}
func (m *CommandProducerSuccess) XXX_Size() int {
	return xxx_messageInfo_CommandProducerSuccess.Size(m)
}
func (m *CommandProducerSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandProducerSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_CommandProducerSuccess proto.InternalMessageInfo

func (m *CommandProducerSuccess) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandProducerSuccess) GetProducerName() string {
	if m != nil && m.ProducerName != nil {
		return *m.ProducerName
	}
	return ""
}

// message
type SingleMessageMetadata struct {
	PayloadSize          *int32   `protobuf:"varint,3,req,name=payload_size,json=payloadSize" json:"payload_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleMessageMetadata) Reset()         { *m = SingleMessageMetadata{} }
func (m *SingleMessageMetadata) String() string { return proto.CompactTextString(m) }
func (*SingleMessageMetadata) ProtoMessage()    {}
func (*SingleMessageMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{11}
}

func (m *SingleMessageMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMessageMetadata.Unmarshal(m, b)
}
func (m *SingleMessageMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMessageMetadata.Marshal(b, m, deterministic)
}
func (m *SingleMessageMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMessageMetadata.Merge(m, src)
}
func (m *SingleMessageMetadata) XXX_Size() int {
	return xxx_messageInfo_SingleMessageMetadata.Size(m)
}
func (m *SingleMessageMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMessageMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMessageMetadata proto.InternalMessageInfo

func (m *SingleMessageMetadata) GetPayloadSize() int32 {
	if m != nil && m.PayloadSize != nil {
		return *m.PayloadSize
	}
	return 0
}

type MessageMetadata struct {
	ProducerName         *string  `protobuf:"bytes,1,req,name=producer_name,json=producerName" json:"producer_name,omitempty"`
	SequenceId           *uint64  `protobuf:"varint,2,req,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	PublishTime          *uint64  `protobuf:"varint,3,req,name=publish_time,json=publishTime" json:"publish_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageMetadata) Reset()         { *m = MessageMetadata{} }
func (m *MessageMetadata) String() string { return proto.CompactTextString(m) }
func (*MessageMetadata) ProtoMessage()    {}
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{12}
}

func (m *MessageMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageMetadata.Unmarshal(m, b)
}
func (m *MessageMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageMetadata.Marshal(b, m, deterministic)
}
func (m *MessageMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageMetadata.Merge(m, src)
}
func (m *MessageMetadata) XXX_Size() int {
	return xxx_messageInfo_MessageMetadata.Size(m)
}
func (m *MessageMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_MessageMetadata proto.InternalMessageInfo

func (m *MessageMetadata) GetProducerName() string {
	if m != nil && m.ProducerName != nil {
		return *m.ProducerName
	}
	return ""
}

func (m *MessageMetadata) GetSequenceId() uint64 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

func (m *MessageMetadata) GetPublishTime() uint64 {
	if m != nil && m.PublishTime != nil {
		return *m.PublishTime
	}
	return 0
}

// send
type CommandSend struct {
	ProducerId           *uint64  `protobuf:"varint,1,req,name=producer_id,json=producerId" json:"producer_id,omitempty"`
	SequenceId           *uint64  `protobuf:"varint,2,req,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	NumMessage           *int32   `protobuf:"varint,3,opt,name=num_message,json=numMessage,def=1" json:"num_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandSend) Reset()         { *m = CommandSend{} }
func (m *CommandSend) String() string { return proto.CompactTextString(m) }
func (*CommandSend) ProtoMessage()    {}
func (*CommandSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{13}
}

func (m *CommandSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSend.Unmarshal(m, b)
}
func (m *CommandSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSend.Marshal(b, m, deterministic)
}
func (m *CommandSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSend.Merge(m, src)
}
func (m *CommandSend) XXX_Size() int {
	return xxx_messageInfo_CommandSend.Size(m)
}
func (m *CommandSend) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSend.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSend proto.InternalMessageInfo

const Default_CommandSend_NumMessage int32 = 1

func (m *CommandSend) GetProducerId() uint64 {
	if m != nil && m.ProducerId != nil {
		return *m.ProducerId
	}
	return 0
}

func (m *CommandSend) GetSequenceId() uint64 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

func (m *CommandSend) GetNumMessage() int32 {
	if m != nil && m.NumMessage != nil {
		return *m.NumMessage
	}
	return Default_CommandSend_NumMessage
}

type CommandSendReceipt struct {
	ProducerId           *uint64        `protobuf:"varint,1,req,name=producer_id,json=producerId" json:"producer_id,omitempty"`
	SequenceId           *uint64        `protobuf:"varint,2,req,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	MessageId            *MessageIdData `protobuf:"bytes,3,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommandSendReceipt) Reset()         { *m = CommandSendReceipt{} }
func (m *CommandSendReceipt) String() string { return proto.CompactTextString(m) }
func (*CommandSendReceipt) ProtoMessage()    {}
func (*CommandSendReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{14}
}

func (m *CommandSendReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSendReceipt.Unmarshal(m, b)
}
func (m *CommandSendReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSendReceipt.Marshal(b, m, deterministic)
}
func (m *CommandSendReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSendReceipt.Merge(m, src)
}
func (m *CommandSendReceipt) XXX_Size() int {
	return xxx_messageInfo_CommandSendReceipt.Size(m)
}
func (m *CommandSendReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSendReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSendReceipt proto.InternalMessageInfo

func (m *CommandSendReceipt) GetProducerId() uint64 {
	if m != nil && m.ProducerId != nil {
		return *m.ProducerId
	}
	return 0
}

func (m *CommandSendReceipt) GetSequenceId() uint64 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

func (m *CommandSendReceipt) GetMessageId() *MessageIdData {
	if m != nil {
		return m.MessageId
	}
	return nil
}

// close
type CommandCloseProducer struct {
	ProducerId           *uint64  `protobuf:"varint,1,req,name=producer_id,json=producerId" json:"producer_id,omitempty"`
	RequestId            *uint64  `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandCloseProducer) Reset()         { *m = CommandCloseProducer{} }
func (m *CommandCloseProducer) String() string { return proto.CompactTextString(m) }
func (*CommandCloseProducer) ProtoMessage()    {}
func (*CommandCloseProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{15}
}

func (m *CommandCloseProducer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandCloseProducer.Unmarshal(m, b)
}
func (m *CommandCloseProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandCloseProducer.Marshal(b, m, deterministic)
}
func (m *CommandCloseProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandCloseProducer.Merge(m, src)
}
func (m *CommandCloseProducer) XXX_Size() int {
	return xxx_messageInfo_CommandCloseProducer.Size(m)
}
func (m *CommandCloseProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandCloseProducer.DiscardUnknown(m)
}

var xxx_messageInfo_CommandCloseProducer proto.InternalMessageInfo

func (m *CommandCloseProducer) GetProducerId() uint64 {
	if m != nil && m.ProducerId != nil {
		return *m.ProducerId
	}
	return 0
}

func (m *CommandCloseProducer) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

//
// message
//
type CommandMessage struct {
	ConsumerId           *uint64        `protobuf:"varint,1,req,name=consumer_id,json=consumerId" json:"consumer_id,omitempty"`
	MessageId            *MessageIdData `protobuf:"bytes,2,req,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommandMessage) Reset()         { *m = CommandMessage{} }
func (m *CommandMessage) String() string { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()    {}
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{16}
}

func (m *CommandMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandMessage.Unmarshal(m, b)
}
func (m *CommandMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandMessage.Marshal(b, m, deterministic)
}
func (m *CommandMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMessage.Merge(m, src)
}
func (m *CommandMessage) XXX_Size() int {
	return xxx_messageInfo_CommandMessage.Size(m)
}
func (m *CommandMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMessage proto.InternalMessageInfo

func (m *CommandMessage) GetConsumerId() uint64 {
	if m != nil && m.ConsumerId != nil {
		return *m.ConsumerId
	}
	return 0
}

func (m *CommandMessage) GetMessageId() *MessageIdData {
	if m != nil {
		return m.MessageId
	}
	return nil
}

type MessageIdData struct {
	LedgerId             *uint64  `protobuf:"varint,1,req,name=ledgerId" json:"ledgerId,omitempty"`
	EntryId              *uint64  `protobuf:"varint,2,req,name=entryId" json:"entryId,omitempty"`
	Partition            *int32   `protobuf:"varint,3,opt,name=partition,def=-1" json:"partition,omitempty"`
	BatchIndex           *int32   `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,def=-1" json:"batch_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageIdData) Reset()         { *m = MessageIdData{} }
func (m *MessageIdData) String() string { return proto.CompactTextString(m) }
func (*MessageIdData) ProtoMessage()    {}
func (*MessageIdData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{17}
}

func (m *MessageIdData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageIdData.Unmarshal(m, b)
}
func (m *MessageIdData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageIdData.Marshal(b, m, deterministic)
}
func (m *MessageIdData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageIdData.Merge(m, src)
}
func (m *MessageIdData) XXX_Size() int {
	return xxx_messageInfo_MessageIdData.Size(m)
}
func (m *MessageIdData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageIdData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageIdData proto.InternalMessageInfo

const Default_MessageIdData_Partition int32 = -1
const Default_MessageIdData_BatchIndex int32 = -1

func (m *MessageIdData) GetLedgerId() uint64 {
	if m != nil && m.LedgerId != nil {
		return *m.LedgerId
	}
	return 0
}

func (m *MessageIdData) GetEntryId() uint64 {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return 0
}

func (m *MessageIdData) GetPartition() int32 {
	if m != nil && m.Partition != nil {
		return *m.Partition
	}
	return Default_MessageIdData_Partition
}

func (m *MessageIdData) GetBatchIndex() int32 {
	if m != nil && m.BatchIndex != nil {
		return *m.BatchIndex
	}
	return Default_MessageIdData_BatchIndex
}

//
// consume
//
// register subscription consumers
type CommandSubscribe struct {
	Topic                *string                           `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	Subscription         *string                           `protobuf:"bytes,2,req,name=subscription" json:"subscription,omitempty"`
	SubType              *CommandSubscribe_SubType         `protobuf:"varint,3,req,name=subType,enum=CommandSubscribe_SubType" json:"subType,omitempty"`
	ConsumerId           *uint64                           `protobuf:"varint,4,req,name=consumer_id,json=consumerId" json:"consumer_id,omitempty"`
	RequestId            *uint64                           `protobuf:"varint,5,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ConsumerName         *string                           `protobuf:"bytes,6,opt,name=consumer_name,json=consumerName" json:"consumer_name,omitempty"`
	InitialPosition      *CommandSubscribe_InitialPosition `protobuf:"varint,13,opt,name=initialPosition,enum=CommandSubscribe_InitialPosition,def=0" json:"initialPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CommandSubscribe) Reset()         { *m = CommandSubscribe{} }
func (m *CommandSubscribe) String() string { return proto.CompactTextString(m) }
func (*CommandSubscribe) ProtoMessage()    {}
func (*CommandSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{18}
}

func (m *CommandSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSubscribe.Unmarshal(m, b)
}
func (m *CommandSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSubscribe.Marshal(b, m, deterministic)
}
func (m *CommandSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSubscribe.Merge(m, src)
}
func (m *CommandSubscribe) XXX_Size() int {
	return xxx_messageInfo_CommandSubscribe.Size(m)
}
func (m *CommandSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSubscribe proto.InternalMessageInfo

const Default_CommandSubscribe_InitialPosition CommandSubscribe_InitialPosition = CommandSubscribe_Latest

func (m *CommandSubscribe) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandSubscribe) GetSubscription() string {
	if m != nil && m.Subscription != nil {
		return *m.Subscription
	}
	return ""
}

func (m *CommandSubscribe) GetSubType() CommandSubscribe_SubType {
	if m != nil && m.SubType != nil {
		return *m.SubType
	}
	return CommandSubscribe_Exclusive
}

func (m *CommandSubscribe) GetConsumerId() uint64 {
	if m != nil && m.ConsumerId != nil {
		return *m.ConsumerId
	}
	return 0
}

func (m *CommandSubscribe) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandSubscribe) GetConsumerName() string {
	if m != nil && m.ConsumerName != nil {
		return *m.ConsumerName
	}
	return ""
}

func (m *CommandSubscribe) GetInitialPosition() CommandSubscribe_InitialPosition {
	if m != nil && m.InitialPosition != nil {
		return *m.InitialPosition
	}
	return Default_CommandSubscribe_InitialPosition
}

// succeed with stats
type CommandConsumerStatsResponse struct {
	RequestId            *uint64  `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ConsumerName         *string  `protobuf:"bytes,5,opt,name=consumer_name,json=consumerName" json:"consumer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandConsumerStatsResponse) Reset()         { *m = CommandConsumerStatsResponse{} }
func (m *CommandConsumerStatsResponse) String() string { return proto.CompactTextString(m) }
func (*CommandConsumerStatsResponse) ProtoMessage()    {}
func (*CommandConsumerStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{19}
}

func (m *CommandConsumerStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandConsumerStatsResponse.Unmarshal(m, b)
}
func (m *CommandConsumerStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandConsumerStatsResponse.Marshal(b, m, deterministic)
}
func (m *CommandConsumerStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandConsumerStatsResponse.Merge(m, src)
}
func (m *CommandConsumerStatsResponse) XXX_Size() int {
	return xxx_messageInfo_CommandConsumerStatsResponse.Size(m)
}
func (m *CommandConsumerStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandConsumerStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandConsumerStatsResponse proto.InternalMessageInfo

func (m *CommandConsumerStatsResponse) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandConsumerStatsResponse) GetConsumerName() string {
	if m != nil && m.ConsumerName != nil {
		return *m.ConsumerName
	}
	return ""
}

// flow
type CommandFlow struct {
	ConsumerId           *uint64  `protobuf:"varint,1,req,name=consumer_id,json=consumerId" json:"consumer_id,omitempty"`
	MessagePermits       *uint32  `protobuf:"varint,2,req,name=messagePermits" json:"messagePermits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandFlow) Reset()         { *m = CommandFlow{} }
func (m *CommandFlow) String() string { return proto.CompactTextString(m) }
func (*CommandFlow) ProtoMessage()    {}
func (*CommandFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{20}
}

func (m *CommandFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandFlow.Unmarshal(m, b)
}
func (m *CommandFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandFlow.Marshal(b, m, deterministic)
}
func (m *CommandFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandFlow.Merge(m, src)
}
func (m *CommandFlow) XXX_Size() int {
	return xxx_messageInfo_CommandFlow.Size(m)
}
func (m *CommandFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandFlow.DiscardUnknown(m)
}

var xxx_messageInfo_CommandFlow proto.InternalMessageInfo

func (m *CommandFlow) GetConsumerId() uint64 {
	if m != nil && m.ConsumerId != nil {
		return *m.ConsumerId
	}
	return 0
}

func (m *CommandFlow) GetMessagePermits() uint32 {
	if m != nil && m.MessagePermits != nil {
		return *m.MessagePermits
	}
	return 0
}

func init() {
	proto.RegisterEnum("ServerError", ServerError_name, ServerError_value)
	proto.RegisterEnum("BaseCommand_Type", BaseCommand_Type_name, BaseCommand_Type_value)
	proto.RegisterEnum("CommandPartitionedTopicMetadataResponse_LookupType", CommandPartitionedTopicMetadataResponse_LookupType_name, CommandPartitionedTopicMetadataResponse_LookupType_value)
	proto.RegisterEnum("CommandLookupTopicResponse_LookupType", CommandLookupTopicResponse_LookupType_name, CommandLookupTopicResponse_LookupType_value)
	proto.RegisterEnum("CommandSubscribe_SubType", CommandSubscribe_SubType_name, CommandSubscribe_SubType_value)
	proto.RegisterEnum("CommandSubscribe_InitialPosition", CommandSubscribe_InitialPosition_name, CommandSubscribe_InitialPosition_value)
	proto.RegisterType((*BaseCommand)(nil), "BaseCommand")
	proto.RegisterType((*CommandSuccess)(nil), "CommandSuccess")
	proto.RegisterType((*CommandError)(nil), "CommandError")
	proto.RegisterType((*CommandConnect)(nil), "CommandConnect")
	proto.RegisterType((*CommandConnected)(nil), "CommandConnected")
	proto.RegisterType((*CommandPartitionedTopicMetadata)(nil), "CommandPartitionedTopicMetadata")
	proto.RegisterType((*CommandPartitionedTopicMetadataResponse)(nil), "CommandPartitionedTopicMetadataResponse")
	proto.RegisterType((*CommandLookupTopic)(nil), "CommandLookupTopic")
	proto.RegisterType((*CommandLookupTopicResponse)(nil), "CommandLookupTopicResponse")
	proto.RegisterType((*CommandProducer)(nil), "CommandProducer")
	proto.RegisterType((*CommandProducerSuccess)(nil), "CommandProducerSuccess")
	proto.RegisterType((*SingleMessageMetadata)(nil), "SingleMessageMetadata")
	proto.RegisterType((*MessageMetadata)(nil), "MessageMetadata")
	proto.RegisterType((*CommandSend)(nil), "CommandSend")
	proto.RegisterType((*CommandSendReceipt)(nil), "CommandSendReceipt")
	proto.RegisterType((*CommandCloseProducer)(nil), "CommandCloseProducer")
	proto.RegisterType((*CommandMessage)(nil), "CommandMessage")
	proto.RegisterType((*MessageIdData)(nil), "MessageIdData")
	proto.RegisterType((*CommandSubscribe)(nil), "CommandSubscribe")
	proto.RegisterType((*CommandConsumerStatsResponse)(nil), "CommandConsumerStatsResponse")
	proto.RegisterType((*CommandFlow)(nil), "CommandFlow")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 1693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4f, 0x6f, 0xdb, 0xc8,
	0x15, 0x37, 0x65, 0xc9, 0xb6, 0x9e, 0xfe, 0x8d, 0xc7, 0x76, 0xcc, 0xcd, 0x36, 0xbb, 0x0e, 0x03,
	0x6f, 0xbd, 0xdb, 0xae, 0xb6, 0x9b, 0xa0, 0x2d, 0x9a, 0xf6, 0x62, 0xc9, 0x4c, 0x21, 0x20, 0x96,
	0xdc, 0xa1, 0x9c, 0x02, 0x45, 0x01, 0x95, 0x22, 0x67, 0x63, 0xc2, 0x14, 0x87, 0xe5, 0x90, 0x89,
	0x9d, 0x63, 0x81, 0xde, 0xf6, 0x7b, 0xf4, 0xb2, 0xe8, 0x07, 0xec, 0xa9, 0x98, 0x21, 0x87, 0x22,
	0x29, 0xc5, 0x0a, 0x8a, 0x9e, 0xa4, 0xf9, 0xbd, 0xbf, 0xf3, 0x9b, 0x79, 0x6f, 0x1e, 0x61, 0x2f,
	0x9c, 0xf7, 0xc3, 0x88, 0xc5, 0xcc, 0xf8, 0x09, 0xa0, 0x35, 0xb0, 0x39, 0x1d, 0xb2, 0xc5, 0xc2,
	0x0e, 0x5c, 0x7c, 0x0a, 0xf5, 0xf8, 0x3e, 0xa4, 0xba, 0x76, 0x52, 0x3b, 0xeb, 0x3e, 0xdf, 0xef,
	0x17, 0x64, 0xfd, 0xe9, 0x7d, 0x48, 0x89, 0x14, 0xe3, 0xaf, 0x61, 0xd7, 0x61, 0x41, 0x40, 0x9d,
	0x58, 0xaf, 0x9d, 0x68, 0x67, 0xad, 0xe7, 0xbd, 0x7e, 0xa6, 0x35, 0x4c, 0x61, 0xa2, 0xe4, 0xf8,
	0x3b, 0x68, 0x66, 0x7f, 0xa9, 0xab, 0x6f, 0x4b, 0xe5, 0xfd, 0x8a, 0x32, 0x75, 0xc9, 0x52, 0x47,
	0x18, 0xf0, 0x64, 0xce, 0x9d, 0xc8, 0x9b, 0x53, 0xbd, 0x5e, 0x36, 0xb0, 0x94, 0x80, 0x2c, 0x75,
	0xf0, 0x2f, 0x61, 0x2f, 0x8c, 0x98, 0x9b, 0x38, 0x34, 0xd2, 0x1b, 0x52, 0x1f, 0x29, 0xfd, 0xab,
	0x0c, 0x27, 0xb9, 0x06, 0x3e, 0x81, 0x3a, 0xa7, 0x81, 0xab, 0xef, 0x48, 0xcd, 0x76, 0xee, 0x99,
	0x06, 0x2e, 0x91, 0x12, 0xfc, 0x1b, 0x68, 0x8b, 0xdf, 0x59, 0x44, 0x1d, 0xea, 0x85, 0xb1, 0xbe,
	0x2b, 0x35, 0x0f, 0x4a, 0x9a, 0xa9, 0x88, 0xb4, 0xf8, 0x72, 0x21, 0x48, 0x59, 0x50, 0xce, 0xed,
	0xb7, 0x54, 0x6f, 0x96, 0x49, 0xb9, 0x4c, 0x61, 0xa2, 0xe4, 0x22, 0x89, 0x1f, 0x7c, 0xf6, 0x5e,
	0x6f, 0x95, 0x93, 0x78, 0xe5, 0xb3, 0xf7, 0x44, 0x4a, 0x84, 0x33, 0x9e, 0x38, 0x0e, 0xe5, 0x5c,
	0xef, 0x94, 0x9d, 0x59, 0x29, 0x4c, 0x94, 0x1c, 0x3f, 0x83, 0x06, 0x8d, 0x22, 0x16, 0xe9, 0x5d,
	0xa9, 0xd8, 0x51, 0x8a, 0xa6, 0x00, 0x49, 0x2a, 0xc3, 0x7f, 0x80, 0xae, 0xe3, 0x33, 0x4e, 0x67,
	0x39, 0x55, 0x3d, 0xa9, 0x7d, 0x94, 0x9f, 0x85, 0x90, 0xe6, 0x7c, 0x75, 0x9c, 0xe2, 0x12, 0x0f,
	0x00, 0x29, 0xbb, 0x99, 0x4a, 0x6b, 0x5f, 0xda, 0x1f, 0x57, 0xa9, 0x56, 0xe9, 0xf5, 0xc2, 0x32,
	0x80, 0xc7, 0xb0, 0x1f, 0xda, 0x51, 0xec, 0xc5, 0x1e, 0x0b, 0x2e, 0x69, 0x6c, 0xbb, 0x76, 0x6c,
	0xeb, 0x47, 0xd2, 0xc9, 0x49, 0xee, 0x44, 0x29, 0x50, 0x77, 0xca, 0x42, 0xcf, 0x51, 0x7a, 0x64,
	0xd5, 0x14, 0xff, 0x00, 0x9f, 0xad, 0x80, 0x84, 0xf2, 0x90, 0x05, 0x9c, 0xea, 0x8f, 0xa4, 0xdf,
	0xb3, 0x8d, 0x7e, 0x33, 0x7d, 0xf2, 0x71, 0x57, 0xf8, 0xd7, 0xd0, 0xf2, 0x19, 0xbb, 0x4d, 0x42,
	0x69, 0xa9, 0x1f, 0x97, 0x6f, 0xc3, 0xeb, 0xa5, 0x88, 0x14, 0xf5, 0xf0, 0x25, 0x1c, 0x14, 0x96,
	0x79, 0x62, 0xba, 0x34, 0xff, 0x7c, 0x9d, 0xb9, 0xca, 0x65, 0x9d, 0x1d, 0xb6, 0xe0, 0xc8, 0x61,
	0x01, 0x4f, 0x16, 0x34, 0xb2, 0x62, 0x3b, 0xe6, 0xb9, 0xc3, 0xc7, 0xd2, 0xe1, 0x93, 0x42, 0x49,
	0xad, 0x2a, 0x91, 0xf5, 0xb6, 0xc6, 0xbf, 0x6b, 0x50, 0x17, 0x55, 0x8d, 0x5b, 0xb0, 0x3b, 0x9c,
	0x8c, 0xc7, 0xe6, 0x70, 0x8a, 0x6a, 0xb8, 0x03, 0xcd, 0x6c, 0x61, 0x5e, 0xa0, 0x6d, 0xb1, 0xb4,
	0xae, 0x07, 0xd6, 0x90, 0x8c, 0x06, 0x26, 0xaa, 0xe3, 0x36, 0xec, 0x5d, 0x91, 0xc9, 0xc5, 0xf5,
	0xd0, 0x24, 0xa8, 0x81, 0xf7, 0xa0, 0x6e, 0x99, 0xe3, 0x0b, 0xb4, 0x83, 0x11, 0xb4, 0xc5, 0xbf,
	0x19, 0x31, 0x87, 0xe6, 0xe8, 0x6a, 0x8a, 0x76, 0x85, 0xd3, 0x4b, 0xd3, 0xb2, 0xce, 0xff, 0x68,
	0xa2, 0xa6, 0x50, 0x7c, 0xf5, 0x7a, 0xf2, 0x67, 0xd4, 0x12, 0xb0, 0x75, 0x3d, 0x1c, 0x9a, 0x96,
	0x85, 0x3a, 0xb8, 0x09, 0x0d, 0x93, 0x90, 0x09, 0x41, 0x5d, 0x8c, 0xa1, 0x3b, 0x7c, 0x3d, 0xb1,
	0xcc, 0x59, 0xee, 0xbe, 0x87, 0x0f, 0x01, 0xa9, 0xd5, 0x4c, 0x19, 0xed, 0x63, 0x1d, 0x0e, 0xaf,
	0xce, 0xc9, 0x74, 0x34, 0x1d, 0x4d, 0xc6, 0xe6, 0xc5, 0xec, 0xd2, 0x9c, 0x9e, 0x5f, 0x9c, 0x4f,
	0xcf, 0xd1, 0x11, 0x7e, 0x0a, 0x4f, 0xd6, 0x49, 0x66, 0xc4, 0xb4, 0xae, 0x26, 0x63, 0xcb, 0x44,
	0x8f, 0x30, 0xc0, 0x4e, 0x4a, 0x3a, 0x3a, 0x16, 0x21, 0xd3, 0xff, 0x8a, 0x11, 0xa4, 0xe3, 0xcf,
	0xe1, 0x78, 0x38, 0x19, 0x5b, 0xd7, 0x97, 0x22, 0xe4, 0xf4, 0x7c, 0x6a, 0x2d, 0x8d, 0x1f, 0x1b,
	0xdf, 0x41, 0xb7, 0x5c, 0x85, 0xf8, 0x09, 0x40, 0x44, 0xff, 0x9e, 0x50, 0x1e, 0xcf, 0x3c, 0x57,
	0xb6, 0xcd, 0x3a, 0x69, 0x66, 0xc8, 0xc8, 0x35, 0x6e, 0xa1, 0x5d, 0xac, 0xc6, 0x0d, 0xea, 0xd8,
	0x50, 0xa5, 0x5c, 0x93, 0xfd, 0xb7, 0xdd, 0xb7, 0x68, 0xf4, 0x8e, 0x46, 0xa5, 0x4a, 0xd6, 0x97,
	0x6d, 0x66, 0xfb, 0xa4, 0x76, 0xd6, 0xcc, 0xbb, 0x8a, 0xf1, 0xdb, 0x3c, 0xbb, 0xac, 0xb1, 0xe2,
	0x53, 0x51, 0xf5, 0x1e, 0x0d, 0xe2, 0xd9, 0x3b, 0x1a, 0x71, 0x8f, 0x05, 0x32, 0x64, 0x53, 0x94,
	0xb7, 0x40, 0xdf, 0xa4, 0xa0, 0xf1, 0x3b, 0x40, 0xd5, 0x8e, 0x2c, 0x4c, 0xb9, 0x0c, 0x5e, 0x35,
	0x4d, 0x51, 0x65, 0xfa, 0x06, 0xbe, 0xdc, 0x50, 0x63, 0xf8, 0x10, 0x1a, 0xb1, 0x2c, 0x9d, 0xd4,
	0x41, 0xba, 0xa8, 0x30, 0x51, 0xab, 0x12, 0xf7, 0x1f, 0x0d, 0x7e, 0xfe, 0x89, 0xc5, 0x8b, 0xbf,
	0x00, 0xc8, 0xcb, 0x97, 0xeb, 0xda, 0x89, 0x76, 0xd6, 0x21, 0x05, 0x64, 0x4d, 0xa8, 0xed, 0x22,
	0xe9, 0x13, 0xd8, 0x8b, 0x54, 0x35, 0x89, 0x07, 0xaa, 0xfb, 0xfc, 0xc5, 0xa7, 0xf6, 0x8d, 0x7e,
	0x56, 0xbf, 0xe2, 0x65, 0xcc, 0x9d, 0x14, 0x4f, 0x48, 0xbc, 0x47, 0x85, 0x13, 0x3a, 0x05, 0x58,
	0x5a, 0xc8, 0x4a, 0x48, 0xaf, 0x11, 0xda, 0x12, 0xf7, 0xf2, 0x95, 0xed, 0xf9, 0xd4, 0x45, 0x9a,
	0x31, 0x02, 0xbc, 0xda, 0x1f, 0xfe, 0x37, 0x1e, 0x7f, 0xaa, 0xc1, 0xe3, 0x8f, 0xf7, 0x1a, 0xfc,
	0x0d, 0xa0, 0x79, 0xc4, 0x6e, 0x69, 0x24, 0x2e, 0x9a, 0xe7, 0xd0, 0xeb, 0xc8, 0x97, 0x04, 0x36,
	0xc9, 0x0a, 0x8e, 0x7f, 0x05, 0x07, 0x55, 0x6c, 0xea, 0x73, 0x39, 0x00, 0x34, 0xc9, 0x3a, 0x11,
	0x1e, 0xac, 0x30, 0xfb, 0xd5, 0x03, 0x8d, 0x6f, 0x3d, 0x99, 0xe5, 0xfd, 0xd5, 0xab, 0x15, 0x53,
	0xe0, 0x7a, 0xb7, 0xcc, 0xf5, 0x8b, 0x12, 0xd7, 0x6d, 0xd8, 0x23, 0xd4, 0xf5, 0x22, 0xea, 0xc4,
	0x68, 0x4b, 0xf6, 0xbb, 0xf4, 0xa6, 0x23, 0xad, 0xc0, 0x7c, 0xcd, 0xf8, 0x51, 0x83, 0x5e, 0xe5,
	0x41, 0xfb, 0x08, 0xef, 0x5f, 0x42, 0x2b, 0x7f, 0x12, 0x73, 0xe2, 0x41, 0x41, 0x23, 0xb7, 0x92,
	0xf8, 0x76, 0x35, 0xf1, 0x67, 0xd0, 0xc9, 0xed, 0x03, 0x7b, 0x91, 0x8e, 0x3a, 0x4d, 0xd2, 0x56,
	0xe0, 0xd8, 0x5e, 0x50, 0xe3, 0xaf, 0xf0, 0x68, 0xfd, 0xf3, 0xba, 0xa9, 0x91, 0xac, 0x78, 0xaf,
	0xc9, 0xdc, 0xcb, 0xde, 0x5f, 0xc2, 0x91, 0xe5, 0x05, 0x6f, 0x7d, 0x9a, 0xcd, 0x27, 0x79, 0xc5,
	0x3e, 0x85, 0x76, 0x68, 0xdf, 0xfb, 0xcc, 0x76, 0x67, 0xdc, 0xfb, 0x90, 0xf6, 0x99, 0x06, 0x69,
	0x65, 0x98, 0xe5, 0x7d, 0xa0, 0xc6, 0x07, 0xe8, 0x55, 0xad, 0x56, 0x62, 0x6a, 0xab, 0x31, 0x05,
	0x6d, 0x5c, 0x64, 0x19, 0x38, 0xb4, 0x40, 0x9b, 0x82, 0x46, 0xae, 0x8c, 0x9d, 0xcc, 0x7d, 0x8f,
	0xdf, 0xcc, 0x62, 0x6f, 0x41, 0x33, 0xe2, 0x5a, 0x19, 0x36, 0xf5, 0x16, 0xd4, 0xe0, 0xd0, 0x2a,
	0xcc, 0x62, 0xd5, 0x93, 0xd0, 0x56, 0x4e, 0x62, 0x63, 0x4c, 0x03, 0x5a, 0x41, 0xb2, 0x98, 0x2d,
	0xdb, 0xaa, 0x76, 0xd6, 0x78, 0xa9, 0x7d, 0x4f, 0x20, 0x48, 0x16, 0xd9, 0x2e, 0x8d, 0x7f, 0x6a,
	0x79, 0x51, 0x16, 0x26, 0xc0, 0xff, 0x43, 0xf0, 0x6f, 0x01, 0xb2, 0xc0, 0xe9, 0x3d, 0x11, 0xcf,
	0x79, 0xb7, 0x9f, 0x85, 0x1d, 0xb9, 0x17, 0xa2, 0xdd, 0x34, 0x17, 0x6a, 0x69, 0xbc, 0x81, 0xc3,
	0x75, 0x13, 0xdb, 0xe6, 0x44, 0x36, 0x34, 0x8a, 0xbf, 0xe5, 0x8f, 0x47, 0x16, 0x5a, 0x78, 0x54,
	0x63, 0x43, 0xc1, 0xa3, 0x82, 0x56, 0x32, 0x17, 0x1e, 0x1f, 0xcc, 0xfc, 0x47, 0x0d, 0x3a, 0x25,
	0x21, 0x7e, 0x0c, 0x7b, 0x3e, 0x75, 0xdf, 0x0a, 0x67, 0x99, 0xfb, 0x7c, 0x2d, 0x0a, 0x9b, 0x06,
	0x71, 0x74, 0x3f, 0x52, 0xb9, 0xaa, 0x25, 0x3e, 0x81, 0x66, 0xde, 0xdc, 0xb3, 0xb3, 0xaa, 0x7d,
	0xfb, 0x3d, 0x59, 0x82, 0xf8, 0x19, 0xb4, 0xe6, 0x76, 0xec, 0xdc, 0xcc, 0xbc, 0xc0, 0xa5, 0x77,
	0xb2, 0xb2, 0x52, 0x1d, 0x90, 0xf0, 0x48, 0xa0, 0xc6, 0x3f, 0xb6, 0xf3, 0x57, 0x2f, 0xff, 0xac,
	0xf8, 0x48, 0xad, 0x1b, 0xd0, 0xce, 0x3e, 0x37, 0x42, 0x19, 0x34, 0x2b, 0xa6, 0x22, 0x86, 0x5f,
	0x88, 0x81, 0x7d, 0x2e, 0x7a, 0x8d, 0xbc, 0xb2, 0xdd, 0xe7, 0x9f, 0xad, 0x7c, 0xb4, 0xf4, 0xad,
	0x54, 0x81, 0x28, 0xcd, 0x2a, 0xc5, 0xf5, 0x15, 0x8a, 0xcb, 0x87, 0xd6, 0x58, 0x53, 0xe6, 0xb9,
	0xbd, 0x2c, 0xb9, 0x9d, 0xb4, 0x89, 0x28, 0x50, 0x96, 0x9c, 0x05, 0x3d, 0x2f, 0xf0, 0x62, 0xcf,
	0xf6, 0xaf, 0x18, 0x4f, 0x59, 0xeb, 0xc8, 0x66, 0xfc, 0x74, 0x35, 0xc3, 0x51, 0x59, 0xf1, 0xe5,
	0xce, 0x6b, 0x3b, 0xa6, 0x3c, 0x26, 0x55, 0x0f, 0x86, 0x2e, 0xde, 0xae, 0x74, 0x13, 0x1d, 0x68,
	0x9a, 0x77, 0x8e, 0x9f, 0x70, 0xef, 0x1d, 0x45, 0x5b, 0xc6, 0x2f, 0xa0, 0x57, 0xf1, 0x22, 0x67,
	0x2e, 0xe9, 0x07, 0x6d, 0x89, 0x46, 0x6c, 0xda, 0x91, 0xef, 0x89, 0x95, 0x66, 0xcc, 0xe1, 0x67,
	0x0f, 0x0d, 0xae, 0x9f, 0xd0, 0xe6, 0xca, 0xfb, 0x6f, 0xac, 0xee, 0xdf, 0x78, 0x93, 0xb7, 0x0b,
	0xf1, 0x7d, 0xb5, 0xf9, 0x5a, 0x7f, 0x05, 0xdd, 0xec, 0xd2, 0x5e, 0xd1, 0x68, 0xe1, 0xc5, 0x5c,
	0x9e, 0x77, 0x87, 0x54, 0xd0, 0x6f, 0xfe, 0x55, 0x87, 0x56, 0x61, 0x3e, 0x13, 0x13, 0xf0, 0x75,
	0x70, 0x1b, 0xb0, 0xf7, 0x81, 0x5c, 0xa3, 0x2d, 0xbc, 0x2f, 0x2e, 0x7c, 0xda, 0x1d, 0x53, 0x48,
	0x93, 0x13, 0xad, 0x18, 0x9d, 0x78, 0x2c, 0xca, 0x3f, 0x45, 0x6b, 0xf8, 0x18, 0x0e, 0xce, 0x93,
	0xf8, 0x86, 0x06, 0xb1, 0xe7, 0xd8, 0x82, 0xb2, 0x54, 0xb0, 0x8d, 0x1f, 0x01, 0x16, 0x02, 0x16,
	0x79, 0x1f, 0x0a, 0x78, 0x5d, 0xc4, 0x52, 0x84, 0x0d, 0x12, 0x7e, 0x8f, 0x1a, 0xf8, 0x00, 0x7a,
	0xd9, 0xe3, 0x3b, 0x66, 0x31, 0xa1, 0xb6, 0x7b, 0x8f, 0x76, 0xf0, 0x29, 0x3c, 0x55, 0x0d, 0x62,
	0xe0, 0x33, 0xe7, 0x96, 0xba, 0x7f, 0x4a, 0x58, 0x6c, 0x9b, 0x77, 0x0e, 0xa5, 0x2e, 0x4d, 0x67,
	0x52, 0xb4, 0x8b, 0xbf, 0x86, 0xd3, 0x07, 0xd5, 0xee, 0x1c, 0x2a, 0x2f, 0x39, 0xda, 0x13, 0x5b,
	0x1a, 0xde, 0x50, 0xe7, 0x96, 0x27, 0x8b, 0xd4, 0xba, 0x29, 0x26, 0xe6, 0xeb, 0x80, 0x27, 0x61,
	0xc8, 0xa2, 0x98, 0xba, 0xd9, 0x60, 0x98, 0x0a, 0x41, 0xe8, 0xcb, 0x47, 0x7e, 0xcc, 0xe2, 0x57,
	0x2c, 0x09, 0x5c, 0xd4, 0x12, 0xe3, 0xbb, 0x55, 0xa8, 0x9c, 0x5c, 0xd2, 0x16, 0xe4, 0xa8, 0x5d,
	0xe5, 0x68, 0x47, 0xec, 0x6c, 0xca, 0xd8, 0xa5, 0x1d, 0xdc, 0x93, 0xf4, 0xe0, 0x39, 0xea, 0x0a,
	0x27, 0xd2, 0xef, 0x54, 0x1c, 0x46, 0x60, 0xc7, 0x6a, 0x33, 0x3d, 0x41, 0x4d, 0xbe, 0x19, 0x41,
	0x0d, 0x12, 0x6e, 0x47, 0xc1, 0x3b, 0xdb, 0xf7, 0xd2, 0x21, 0x4e, 0x5c, 0x0a, 0xb4, 0x2f, 0xa8,
	0x1d, 0x05, 0x0e, 0x5b, 0x84, 0x76, 0xec, 0xcd, 0x7d, 0x6a, 0x39, 0x37, 0x74, 0x61, 0x23, 0x2c,
	0xce, 0x42, 0x25, 0x71, 0xce, 0xb9, 0xf7, 0x36, 0xdb, 0xca, 0x01, 0x36, 0xe0, 0x8b, 0x69, 0x64,
	0x07, 0xdc, 0x76, 0x44, 0xda, 0x43, 0xc6, 0x22, 0x57, 0x44, 0x66, 0xcb, 0x5c, 0x0f, 0x8b, 0xa1,
	0xee, 0x02, 0x71, 0x95, 0x13, 0x8e, 0x8e, 0x06, 0x3b, 0x7f, 0xa9, 0xf7, 0x7f, 0x1f, 0xce, 0xff,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xa1, 0x5c, 0xcc, 0x78, 0x11, 0x00, 0x00,
}
