// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseCommand_Type int32

const (
	BaseCommand_CONNECT              BaseCommand_Type = 2
	BaseCommand_CONNECTED            BaseCommand_Type = 3
	BaseCommand_PARTITIONED_METADATA BaseCommand_Type = 21
)

var BaseCommand_Type_name = map[int32]string{
	2:  "CONNECT",
	3:  "CONNECTED",
	21: "PARTITIONED_METADATA",
}

var BaseCommand_Type_value = map[string]int32{
	"CONNECT":              2,
	"CONNECTED":            3,
	"PARTITIONED_METADATA": 21,
}

func (x BaseCommand_Type) Enum() *BaseCommand_Type {
	p := new(BaseCommand_Type)
	*p = x
	return p
}

func (x BaseCommand_Type) String() string {
	return proto.EnumName(BaseCommand_Type_name, int32(x))
}

func (x *BaseCommand_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BaseCommand_Type_value, data, "BaseCommand_Type")
	if err != nil {
		return err
	}
	*x = BaseCommand_Type(value)
	return nil
}

func (BaseCommand_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0, 0}
}

type CommandPartitionedTopicMetadataResponse_LookupType int32

const (
	CommandPartitionedTopicMetadataResponse_Success CommandPartitionedTopicMetadataResponse_LookupType = 0
	CommandPartitionedTopicMetadataResponse_Failed  CommandPartitionedTopicMetadataResponse_LookupType = 1
)

var CommandPartitionedTopicMetadataResponse_LookupType_name = map[int32]string{
	0: "Success",
	1: "Failed",
}

var CommandPartitionedTopicMetadataResponse_LookupType_value = map[string]int32{
	"Success": 0,
	"Failed":  1,
}

func (x CommandPartitionedTopicMetadataResponse_LookupType) Enum() *CommandPartitionedTopicMetadataResponse_LookupType {
	p := new(CommandPartitionedTopicMetadataResponse_LookupType)
	*p = x
	return p
}

func (x CommandPartitionedTopicMetadataResponse_LookupType) String() string {
	return proto.EnumName(CommandPartitionedTopicMetadataResponse_LookupType_name, int32(x))
}

func (x *CommandPartitionedTopicMetadataResponse_LookupType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandPartitionedTopicMetadataResponse_LookupType_value, data, "CommandPartitionedTopicMetadataResponse_LookupType")
	if err != nil {
		return err
	}
	*x = CommandPartitionedTopicMetadataResponse_LookupType(value)
	return nil
}

func (CommandPartitionedTopicMetadataResponse_LookupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4, 0}
}

// protocol unit
type BaseCommand struct {
	Type                      *BaseCommand_Type                        `protobuf:"varint,1,req,name=type,enum=BaseCommand_Type" json:"type,omitempty"`
	Connect                   *CommandConnect                          `protobuf:"bytes,2,opt,name=connect" json:"connect,omitempty"`
	Connected                 *CommandConnected                        `protobuf:"bytes,3,opt,name=connected" json:"connected,omitempty"`
	PartitionMetadata         *CommandPartitionedTopicMetadata         `protobuf:"bytes,21,opt,name=partitionMetadata" json:"partitionMetadata,omitempty"`
	PartitionMetadataResponse *CommandPartitionedTopicMetadataResponse `protobuf:"bytes,22,opt,name=partitionMetadataResponse" json:"partitionMetadataResponse,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                 `json:"-"`
	XXX_unrecognized          []byte                                   `json:"-"`
	XXX_sizecache             int32                                    `json:"-"`
}

func (m *BaseCommand) Reset()         { *m = BaseCommand{} }
func (m *BaseCommand) String() string { return proto.CompactTextString(m) }
func (*BaseCommand) ProtoMessage()    {}
func (*BaseCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *BaseCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseCommand.Unmarshal(m, b)
}
func (m *BaseCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseCommand.Marshal(b, m, deterministic)
}
func (m *BaseCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseCommand.Merge(m, src)
}
func (m *BaseCommand) XXX_Size() int {
	return xxx_messageInfo_BaseCommand.Size(m)
}
func (m *BaseCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseCommand.DiscardUnknown(m)
}

var xxx_messageInfo_BaseCommand proto.InternalMessageInfo

func (m *BaseCommand) GetType() BaseCommand_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BaseCommand_CONNECT
}

func (m *BaseCommand) GetConnect() *CommandConnect {
	if m != nil {
		return m.Connect
	}
	return nil
}

func (m *BaseCommand) GetConnected() *CommandConnected {
	if m != nil {
		return m.Connected
	}
	return nil
}

func (m *BaseCommand) GetPartitionMetadata() *CommandPartitionedTopicMetadata {
	if m != nil {
		return m.PartitionMetadata
	}
	return nil
}

func (m *BaseCommand) GetPartitionMetadataResponse() *CommandPartitionedTopicMetadataResponse {
	if m != nil {
		return m.PartitionMetadataResponse
	}
	return nil
}

// handshake
type CommandConnect struct {
	ClientVersion        *string  `protobuf:"bytes,1,req,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandConnect) Reset()         { *m = CommandConnect{} }
func (m *CommandConnect) String() string { return proto.CompactTextString(m) }
func (*CommandConnect) ProtoMessage()    {}
func (*CommandConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *CommandConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandConnect.Unmarshal(m, b)
}
func (m *CommandConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandConnect.Marshal(b, m, deterministic)
}
func (m *CommandConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandConnect.Merge(m, src)
}
func (m *CommandConnect) XXX_Size() int {
	return xxx_messageInfo_CommandConnect.Size(m)
}
func (m *CommandConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandConnect.DiscardUnknown(m)
}

var xxx_messageInfo_CommandConnect proto.InternalMessageInfo

func (m *CommandConnect) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

type CommandConnected struct {
	ServerVersion        *string  `protobuf:"bytes,1,req,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandConnected) Reset()         { *m = CommandConnected{} }
func (m *CommandConnected) String() string { return proto.CompactTextString(m) }
func (*CommandConnected) ProtoMessage()    {}
func (*CommandConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *CommandConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandConnected.Unmarshal(m, b)
}
func (m *CommandConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandConnected.Marshal(b, m, deterministic)
}
func (m *CommandConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandConnected.Merge(m, src)
}
func (m *CommandConnected) XXX_Size() int {
	return xxx_messageInfo_CommandConnected.Size(m)
}
func (m *CommandConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandConnected.DiscardUnknown(m)
}

var xxx_messageInfo_CommandConnected proto.InternalMessageInfo

func (m *CommandConnected) GetServerVersion() string {
	if m != nil && m.ServerVersion != nil {
		return *m.ServerVersion
	}
	return ""
}

// partitioned topic metadata
type CommandPartitionedTopicMetadata struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	RequestId            *uint64  `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandPartitionedTopicMetadata) Reset()         { *m = CommandPartitionedTopicMetadata{} }
func (m *CommandPartitionedTopicMetadata) String() string { return proto.CompactTextString(m) }
func (*CommandPartitionedTopicMetadata) ProtoMessage()    {}
func (*CommandPartitionedTopicMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *CommandPartitionedTopicMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Unmarshal(m, b)
}
func (m *CommandPartitionedTopicMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Marshal(b, m, deterministic)
}
func (m *CommandPartitionedTopicMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPartitionedTopicMetadata.Merge(m, src)
}
func (m *CommandPartitionedTopicMetadata) XXX_Size() int {
	return xxx_messageInfo_CommandPartitionedTopicMetadata.Size(m)
}
func (m *CommandPartitionedTopicMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPartitionedTopicMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPartitionedTopicMetadata proto.InternalMessageInfo

func (m *CommandPartitionedTopicMetadata) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *CommandPartitionedTopicMetadata) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type CommandPartitionedTopicMetadataResponse struct {
	Partitions           *uint32                                             `protobuf:"varint,1,opt,name=partitions" json:"partitions,omitempty"`
	RequestId            *int64                                              `protobuf:"varint,2,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	Response             *CommandPartitionedTopicMetadataResponse_LookupType `protobuf:"varint,3,opt,name=response,enum=CommandPartitionedTopicMetadataResponse_LookupType" json:"response,omitempty"`
	Message              *string                                             `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *CommandPartitionedTopicMetadataResponse) Reset() {
	*m = CommandPartitionedTopicMetadataResponse{}
}
func (m *CommandPartitionedTopicMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*CommandPartitionedTopicMetadataResponse) ProtoMessage()    {}
func (*CommandPartitionedTopicMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *CommandPartitionedTopicMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Unmarshal(m, b)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Marshal(b, m, deterministic)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Merge(m, src)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_CommandPartitionedTopicMetadataResponse.Size(m)
}
func (m *CommandPartitionedTopicMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPartitionedTopicMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPartitionedTopicMetadataResponse proto.InternalMessageInfo

func (m *CommandPartitionedTopicMetadataResponse) GetPartitions() uint32 {
	if m != nil && m.Partitions != nil {
		return *m.Partitions
	}
	return 0
}

func (m *CommandPartitionedTopicMetadataResponse) GetRequestId() int64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CommandPartitionedTopicMetadataResponse) GetResponse() CommandPartitionedTopicMetadataResponse_LookupType {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return CommandPartitionedTopicMetadataResponse_Success
}

func (m *CommandPartitionedTopicMetadataResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("BaseCommand_Type", BaseCommand_Type_name, BaseCommand_Type_value)
	proto.RegisterEnum("CommandPartitionedTopicMetadataResponse_LookupType", CommandPartitionedTopicMetadataResponse_LookupType_name, CommandPartitionedTopicMetadataResponse_LookupType_value)
	proto.RegisterType((*BaseCommand)(nil), "BaseCommand")
	proto.RegisterType((*CommandConnect)(nil), "CommandConnect")
	proto.RegisterType((*CommandConnected)(nil), "CommandConnected")
	proto.RegisterType((*CommandPartitionedTopicMetadata)(nil), "CommandPartitionedTopicMetadata")
	proto.RegisterType((*CommandPartitionedTopicMetadataResponse)(nil), "CommandPartitionedTopicMetadataResponse")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0xc4, 0x4e, 0x4a, 0xea, 0x17, 0x25, 0x38, 0xab, 0x16, 0x2d, 0x07, 0xc0, 0xb2, 0x14, 0x61,
	0x2e, 0x46, 0x0a, 0x07, 0x84, 0xc4, 0xc5, 0x38, 0x46, 0x8a, 0x44, 0x9d, 0x6a, 0xb1, 0x7a, 0x8d,
	0x16, 0xef, 0x03, 0x59, 0x34, 0xde, 0xc5, 0xbb, 0xa9, 0xd4, 0x3f, 0xc0, 0x8f, 0xe6, 0x84, 0xfc,
	0xd5, 0x86, 0x14, 0xd4, 0xde, 0xfc, 0xe6, 0xcd, 0xcc, 0xca, 0x33, 0x0f, 0x8e, 0xd5, 0xd7, 0x50,
	0x55, 0xd2, 0x48, 0xff, 0xd7, 0x00, 0xc6, 0x1f, 0xb9, 0xc6, 0x58, 0x6e, 0xb7, 0xbc, 0x14, 0x64,
	0x0e, 0x43, 0x73, 0xad, 0x90, 0x5a, 0x9e, 0x1d, 0x4c, 0x17, 0xb3, 0x70, 0x6f, 0x17, 0x66, 0xd7,
	0x0a, 0x59, 0xb3, 0x26, 0xaf, 0x61, 0x94, 0xcb, 0xb2, 0xc4, 0xdc, 0x50, 0xdb, 0xb3, 0x82, 0xf1,
	0xe2, 0x49, 0xd8, 0xb1, 0xe2, 0x16, 0x66, 0xfd, 0x9e, 0xbc, 0x01, 0xa7, 0xfb, 0x44, 0x41, 0x07,
	0x0d, 0x79, 0x76, 0x40, 0x46, 0xc1, 0x6e, 0x39, 0x24, 0x85, 0x99, 0xe2, 0x95, 0x29, 0x4c, 0x21,
	0xcb, 0x33, 0x34, 0x5c, 0x70, 0xc3, 0xe9, 0x69, 0x23, 0xf4, 0x7a, 0xe1, 0x79, 0x4f, 0x40, 0x91,
	0x49, 0x55, 0xe4, 0x3d, 0x8f, 0xdd, 0x95, 0x92, 0x6f, 0xf0, 0xec, 0x0e, 0xc8, 0x50, 0x2b, 0x59,
	0x6a, 0xa4, 0x4f, 0x1b, 0xdf, 0xe0, 0x5e, 0xdf, 0x8e, 0xcf, 0xfe, 0x6f, 0xe5, 0x7f, 0x80, 0x61,
	0x9d, 0x10, 0x19, 0xc3, 0x28, 0x5e, 0xa7, 0x69, 0x12, 0x67, 0xae, 0x4d, 0x26, 0xe0, 0x74, 0x43,
	0xb2, 0x74, 0x07, 0x84, 0xc2, 0xc9, 0x79, 0xc4, 0xb2, 0x55, 0xb6, 0x5a, 0xa7, 0xc9, 0x72, 0x73,
	0x96, 0x64, 0xd1, 0x32, 0xca, 0x22, 0xf7, 0xd4, 0x7f, 0x07, 0xd3, 0xbf, 0x43, 0x21, 0x73, 0x98,
	0xe6, 0x97, 0x05, 0x96, 0x66, 0x73, 0x85, 0x95, 0x2e, 0x64, 0xd9, 0x94, 0xe2, 0xb0, 0x49, 0x8b,
	0x5e, 0xb4, 0xa0, 0xff, 0x1e, 0xdc, 0xc3, 0x34, 0x6b, 0xa9, 0xc6, 0xea, 0x0a, 0xab, 0x43, 0x69,
	0x8b, 0xf6, 0xd2, 0x0b, 0x78, 0x79, 0xcf, 0x7f, 0x93, 0x13, 0x38, 0x32, 0x35, 0xd0, 0x19, 0xb4,
	0x03, 0x79, 0x0e, 0x50, 0xe1, 0xcf, 0x1d, 0x6a, 0xb3, 0x29, 0x04, 0xb5, 0x3d, 0x3b, 0x18, 0x32,
	0xa7, 0x43, 0x56, 0xc2, 0xff, 0x6d, 0xc1, 0xab, 0x07, 0x06, 0x4a, 0x5e, 0x00, 0xdc, 0x44, 0xaa,
	0xa9, 0xe5, 0x59, 0xc1, 0x84, 0xed, 0x21, 0xff, 0x78, 0x6a, 0xb0, 0xf7, 0x14, 0x59, 0xc3, 0x71,
	0xd5, 0x77, 0x59, 0x1f, 0xd7, 0x74, 0xf1, 0xf6, 0xa1, 0x5d, 0x86, 0x9f, 0xa5, 0xfc, 0xb1, 0x53,
	0xcd, 0x55, 0xdf, 0x98, 0x10, 0x0a, 0xa3, 0x2d, 0x6a, 0xcd, 0xbf, 0x23, 0x3d, 0xf2, 0xac, 0xc0,
	0x61, 0xfd, 0xe8, 0xcf, 0x01, 0x6e, 0x15, 0x75, 0xcb, 0x5f, 0x76, 0x79, 0x8e, 0x5a, 0xbb, 0x8f,
	0x08, 0xc0, 0xe3, 0x4f, 0xbc, 0xb8, 0x44, 0xe1, 0x5a, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb6,
	0xf2, 0x7d, 0x6a, 0x5c, 0x03, 0x00, 0x00,
}
